/*
MIT License

Copyright (c) 2026 Kama contributors

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/
#ifndef KAMA_H
#define KAMA_H
/* MIT licensed. Generated by tools/generate_header.py; edit src/ instead. */
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#ifdef __cplusplus
#include <type_traits>
#define KAMA_CHECK_VALUE(T) static_assert(std::is_trivially_copyable<T>::value && std::is_trivially_default_constructible<T>::value, "Kama values must be trivial C-compatible types");
#else
#define KAMA_CHECK_VALUE(T)
#endif
#if defined(_MSC_VER)
#include <intrin.h>
#define KAMA_INLINE __forceinline
#define KAMA_ALIGNOF(T) __alignof(T)
#define KAMA_UNUSED
#elif defined(__GNUC__) || defined(__clang__)
#define KAMA_INLINE inline __attribute__((always_inline))
#define KAMA_ALIGNOF(T) __alignof__(T)
#define KAMA_UNUSED __attribute__((unused))
#else
#define KAMA_INLINE inline
#define KAMA_ALIGNOF(T) _Alignof(T)
#define KAMA_UNUSED
#endif
#define KAMA_FN static KAMA_UNUSED inline
#define KAMA_HOT static KAMA_UNUSED KAMA_INLINE
#ifndef KAMA_LOAD_PERCENT
#define KAMA_LOAD_PERCENT 85
#endif
#if KAMA_LOAD_PERCENT < 25 || KAMA_LOAD_PERCENT > 95
#error "KAMA_LOAD_PERCENT must be between 25 and 95"
#endif
#define KAMA_LOAD_FACTOR (KAMA_LOAD_PERCENT / 100.0)
#define KAMA_CTRL_EMPTY ((int8_t)-1)
#define KAMA_CTRL_DELETED ((int8_t)-2)
#define KAMA_H2(h) ((int8_t)((uint64_t)(h) >> 57))
#ifndef KAMA_SEED
#define KAMA_SEED UINT64_C(0)
#endif
#ifndef KAMA_LINEAR_PROBING
#define KAMA_LINEAR_PROBING 0
#endif
#ifndef KAMA_LOOKUP_PREFETCH
#define KAMA_LOOKUP_PREFETCH 0
#endif
#ifndef KAMA_BATCH_SIZE
#define KAMA_BATCH_SIZE 16
#endif
#if KAMA_BATCH_SIZE < 1
#error "KAMA_BATCH_SIZE must be positive"
#endif
#if defined(__GNUC__) || defined(__clang__)
#define KAMA_PREFETCH(p) __builtin_prefetch((p), 0, 1)
#else
#define KAMA_PREFETCH(p) ((void)(p))
#endif

/* Width is independently selectable; unavailable ISA paths fall back to SWAR. */
#ifndef KAMA_GROUP_WIDTH
#if defined(__AVX512BW__) && !defined(KAMA_FORCE_SCALAR)
#define KAMA_GROUP_WIDTH 64
#elif defined(__AVX2__) && !defined(KAMA_FORCE_SCALAR)
#define KAMA_GROUP_WIDTH 32
#elif defined(KAMA_NEON8)
#define KAMA_GROUP_WIDTH 8
#elif defined(KAMA_FORCE_SCALAR)
#define KAMA_GROUP_WIDTH 8
#else
#define KAMA_GROUP_WIDTH 16
#endif
#endif
#if KAMA_GROUP_WIDTH != 8 && KAMA_GROUP_WIDTH != 16 && KAMA_GROUP_WIDTH != 32 && KAMA_GROUP_WIDTH != 64
#error "KAMA_GROUP_WIDTH must be 8, 16, 32, or 64"
#endif
#if !defined(KAMA_FORCE_SCALAR) && defined(__AVX512BW__) && KAMA_GROUP_WIDTH == 64
#include <immintrin.h>
#define KAMA_SIMD_AVX512 1
typedef __m512i kama_group_t;
#elif !defined(KAMA_FORCE_SCALAR) && defined(__AVX2__) && KAMA_GROUP_WIDTH == 32
#include <immintrin.h>
#define KAMA_SIMD_AVX 1
typedef __m256i kama_group_t;
#elif !defined(KAMA_FORCE_SCALAR) && (defined(__SSE2__) || defined(_M_X64) || (defined(_M_IX86_FP) && _M_IX86_FP >= 2)) && KAMA_GROUP_WIDTH == 16
#include <emmintrin.h>
#define KAMA_SIMD_SSE 1
typedef __m128i kama_group_t;
#elif !defined(KAMA_FORCE_SCALAR) && (defined(__ARM_NEON) || defined(__ARM_NEON__)) && (KAMA_GROUP_WIDTH == 16 || KAMA_GROUP_WIDTH == 8)
#include <arm_neon.h>
#define KAMA_SIMD_NEON 1
#if KAMA_GROUP_WIDTH == 8
typedef uint8x8_t kama_group_t;
#else
typedef uint8x16_t kama_group_t;
#endif
#else
#define KAMA_ARCH_GENERIC 1
typedef struct { uint64_t words[KAMA_GROUP_WIDTH / 8]; } kama_group_t;
#endif
typedef uint64_t kama_simd_mask;
#if KAMA_GROUP_WIDTH == 8
#define KAMA_MASK_ALL UINT64_C(0x8080808080808080)
#elif defined(KAMA_SIMD_NEON) && KAMA_GROUP_WIDTH == 16
#define KAMA_MASK_ALL UINT64_C(0x8888888888888888)
#else
#define KAMA_MASK_ALL (UINT64_MAX >> (64 - KAMA_GROUP_WIDTH))
#endif
KAMA_FN unsigned kama_ctz(uint64_t x) {
#if defined(__GNUC__) || defined(__clang__)
    return (unsigned)__builtin_ctzll(x);
#elif defined(_MSC_VER) && defined(_M_X64)
    unsigned long n; _BitScanForward64(&n, x); return (unsigned)n;
#else
    unsigned n = 0; while (!(x & 1)) { x >>= 1; ++n; } return n;
#endif
}
KAMA_FN unsigned kama_mask_first(uint64_t mask) {
#if KAMA_GROUP_WIDTH == 8
    return kama_ctz(mask) / 8;
#elif defined(KAMA_SIMD_NEON) && KAMA_GROUP_WIDTH == 16
    return kama_ctz(mask) / 4;
#else
    return kama_ctz(mask);
#endif
}
KAMA_FN unsigned kama_mask_last(uint64_t mask) {
    unsigned n;
#if defined(__GNUC__) || defined(__clang__)
    n = 63u - (unsigned)__builtin_clzll(mask);
#elif defined(_MSC_VER) && defined(_M_X64)
    unsigned long bit; _BitScanReverse64(&bit, mask); n = (unsigned)bit;
#else
    n = 0; while (mask >>= 1) ++n;
#endif
#if KAMA_GROUP_WIDTH == 8
    return n / 8;
#elif defined(KAMA_SIMD_NEON) && KAMA_GROUP_WIDTH == 16
    return n / 4;
#else
    return n;
#endif
}
KAMA_FN uint64_t kama_read_le64(const void *p) {
    uint64_t x; memcpy(&x, p, 8);
#if defined(__BYTE_ORDER__) && __BYTE_ORDER__ == __ORDER_BIG_ENDIAN__
    x = ((x & UINT64_C(0xff00ff00ff00ff00)) >> 8) | ((x & UINT64_C(0x00ff00ff00ff00ff)) << 8);
    x = ((x & UINT64_C(0xffff0000ffff0000)) >> 16) | ((x & UINT64_C(0x0000ffff0000ffff)) << 16);
    x = (x >> 32) | (x << 32);
#endif
    return x;
}
KAMA_FN kama_group_t kama_group_load(const int8_t *p) {
#if defined(KAMA_SIMD_AVX512)
    return _mm512_loadu_si512((const void *)p);
#elif defined(KAMA_SIMD_AVX)
    return _mm256_loadu_si256((const __m256i *)(const void *)p);
#elif defined(KAMA_SIMD_SSE)
    return _mm_loadu_si128((const __m128i *)(const void *)p);
#elif defined(KAMA_SIMD_NEON) && KAMA_GROUP_WIDTH == 8
    return vld1_u8((const uint8_t *)p);
#elif defined(KAMA_SIMD_NEON)
    return vld1q_u8((const uint8_t *)p);
#else
    kama_group_t g;
    for (size_t i = 0; i < KAMA_GROUP_WIDTH / 8; ++i) g.words[i] = kama_read_le64(p + 8 * i);
    return g;
#endif
}
KAMA_FN uint64_t kama_pack_signs(uint64_t x) {
    return ((x & UINT64_C(0x8080808080808080)) >> 7) * UINT64_C(0x0102040810204080) >> 56;
}
#if defined(KAMA_SIMD_NEON) && KAMA_GROUP_WIDTH == 16
KAMA_FN uint64_t kama_neon_mask(uint8x16_t cmp) {
    /* Each 00/ff comparison byte contributes one bit in a four-bit lane.
     * Narrowing packs both halves without horizontal reductions. */
    uint8x8_t packed = vshrn_n_u16(vreinterpretq_u16_u8(cmp), 4);
    return vget_lane_u64(vreinterpret_u64_u8(packed), 0) & KAMA_MASK_ALL;
}
#endif
KAMA_FN uint64_t kama_group_match(kama_group_t g, int8_t tag) {
#if defined(KAMA_SIMD_AVX512)
    return _mm512_cmpeq_epi8_mask(g, _mm512_set1_epi8(tag));
#elif defined(KAMA_SIMD_AVX)
    return (uint32_t)_mm256_movemask_epi8(_mm256_cmpeq_epi8(g, _mm256_set1_epi8(tag)));
#elif defined(KAMA_SIMD_SSE)
    return (uint32_t)_mm_movemask_epi8(_mm_cmpeq_epi8(g, _mm_set1_epi8(tag)));
#elif defined(KAMA_SIMD_NEON) && KAMA_GROUP_WIDTH == 8
    return vget_lane_u64(vreinterpret_u64_u8(vceq_u8(g, vdup_n_u8((uint8_t)tag))), 0) & KAMA_MASK_ALL;
#elif defined(KAMA_SIMD_NEON)
    return kama_neon_mask(vceqq_u8(g, vdupq_n_u8((uint8_t)tag)));
#else
    uint64_t result = 0;
    for (size_t i = 0; i < KAMA_GROUP_WIDTH / 8; ++i) {
        uint64_t x = g.words[i] ^ (UINT64_C(0x0101010101010101) * (uint8_t)tag);
        uint64_t z = ~(((x & UINT64_C(0x7f7f7f7f7f7f7f7f)) + UINT64_C(0x7f7f7f7f7f7f7f7f)) | x | UINT64_C(0x7f7f7f7f7f7f7f7f));
#if KAMA_GROUP_WIDTH == 8
        result = z & KAMA_MASK_ALL;
#else
        result |= kama_pack_signs(z) << (8 * i);
#endif
    }
    return result;
#endif
}
KAMA_FN uint64_t kama_group_available(kama_group_t g) {
#if defined(KAMA_SIMD_AVX512)
    return _mm512_movepi8_mask(g);
#elif defined(KAMA_SIMD_AVX)
    return (uint32_t)_mm256_movemask_epi8(g);
#elif defined(KAMA_SIMD_SSE)
    return (uint32_t)_mm_movemask_epi8(g);
#elif defined(KAMA_SIMD_NEON) && KAMA_GROUP_WIDTH == 8
    return vget_lane_u64(vreinterpret_u64_u8(g), 0) & KAMA_MASK_ALL;
#elif defined(KAMA_SIMD_NEON)
    return kama_neon_mask(vreinterpretq_u8_s8(vshrq_n_s8(vreinterpretq_s8_u8(g), 7)));
#else
    uint64_t result = 0;
    for (size_t i = 0; i < KAMA_GROUP_WIDTH / 8; ++i) {
#if KAMA_GROUP_WIDTH == 8
        result = g.words[i] & KAMA_MASK_ALL;
#else
        result |= kama_pack_signs(g.words[i]) << (8 * i);
#endif
    }
    return result;
#endif
}

typedef enum { KAMA_ERROR = -1, KAMA_UPDATED = 0, KAMA_INSERTED = 1 } kama_result_t;
typedef struct { const char *data; size_t len; } kama_key_t;
typedef struct { uint32_t hash, len; } kama_meta_t;
typedef union { const char *ptr; uint64_t inline_key; } kama_string_storage_t;
/* Packed strings reuse the adjacent key+metadata words for exact 16-byte keys.
 * A separate bit preserves all seven H2 bits and makes every key bit pattern valid. */
KAMA_FN int kama_is_inline16(const int8_t *ctrl, size_t cap, size_t i) {
    return (((const uint8_t *)ctrl)[cap + KAMA_GROUP_WIDTH + i / 8] >> (i % 8)) & 1;
}
KAMA_FN void kama_set_inline16(int8_t *ctrl, size_t cap, size_t i, int value) {
    uint8_t *p = (uint8_t *)ctrl + cap + KAMA_GROUP_WIDTH + i / 8;
    *p = (uint8_t)((*p & ~(1u << (i % 8))) | ((unsigned)value << (i % 8)));
}
typedef struct {
    uint64_t probe_groups, key_comparisons, rehashes, migrated_entries;
    size_t allocated_bytes, peak_allocated_bytes;
} kama_stats_t;
typedef void *(*kama_allocate_fn)(void *context, size_t bytes, size_t alignment);
typedef void (*kama_deallocate_fn)(void *context, void *ptr, size_t bytes, size_t alignment);
typedef uint64_t (*kama_hash_fn)(const void *key, size_t len, uint64_t seed, void *context);
typedef int (*kama_equal_fn)(const void *a, const void *b, size_t len, void *context);
typedef struct {
    kama_allocate_fn allocate;
    kama_deallocate_fn deallocate;
    void *allocator_context;
    uint64_t seed;
    int copy_keys;
    kama_hash_fn hash;
    kama_equal_fn equal;
    void *key_context;
    kama_stats_t *stats; /* Counters only compiled when KAMA_ENABLE_STATS is defined. */
} kama_options_t;
#ifdef KAMA_ENABLE_STATS
#define KAMA_STAT(m, field, amount) do { if ((m)->options.stats) (m)->options.stats->field += (amount); } while (0)
#else
#define KAMA_STAT(m, field, amount) ((void)0)
#endif
KAMA_FN int kama_add_size(size_t a, size_t b, size_t *out) {
    if (a > SIZE_MAX - b) return 0;
    *out = a + b; return 1;
}
KAMA_FN int kama_mul_size(size_t a, size_t b, size_t *out) {
    if (b && a > SIZE_MAX / b) return 0;
    *out = a * b; return 1;
}
KAMA_FN void *kama_allocate(const kama_options_t *o, size_t bytes, size_t alignment) {
    void *p;
    if (o->allocate) p = o->allocate(o->allocator_context, bytes, alignment);
    else {
        size_t total;
        if (!kama_add_size(bytes, alignment - 1 + sizeof(void *), &total)) return NULL;
        void *raw = malloc(total);
        if (!raw) return NULL;
        p = (void *)(((uintptr_t)raw + sizeof(void *) + alignment - 1) & ~(uintptr_t)(alignment - 1));
        ((void **)p)[-1] = raw;
    }
#ifdef KAMA_ENABLE_STATS
    if (p && o->stats) {
        o->stats->allocated_bytes += bytes;
        if (o->stats->allocated_bytes > o->stats->peak_allocated_bytes)
            o->stats->peak_allocated_bytes = o->stats->allocated_bytes;
    }
#endif
    return p;
}
KAMA_FN void kama_deallocate(const kama_options_t *o, void *p, size_t bytes, size_t alignment) {
    if (!p) return;
    if (o->deallocate) o->deallocate(o->allocator_context, p, bytes, alignment);
    else free(((void **)p)[-1]);
#ifdef KAMA_ENABLE_STATS
    if (o->stats) o->stats->allocated_bytes -= bytes;
#endif
    (void)bytes; (void)alignment;
}
KAMA_FN size_t kama_threshold(size_t cap) {
    return (cap / 100) * KAMA_LOAD_PERCENT + ((cap % 100) * KAMA_LOAD_PERCENT) / 100;
}
KAMA_FN int kama_round_capacity(size_t request, size_t *out) {
    size_t cap = KAMA_GROUP_WIDTH;
    while (cap < request) {
        if (cap > SIZE_MAX / 2 || cap > UINT32_MAX) return 0;
        cap *= 2;
    }
    *out = cap; return 1;
}
KAMA_FN int kama_capacity_for(size_t entries, size_t *out) {
    size_t cap = KAMA_GROUP_WIDTH;
    while (kama_threshold(cap) < entries) {
        if (cap > SIZE_MAX / 2 || cap > UINT32_MAX) return 0;
        cap *= 2;
    }
    *out = cap; return 1;
}
KAMA_FN void kama_set_ctrl(int8_t *ctrl, size_t cap, size_t i, int8_t tag) {
    ctrl[i] = tag;
    if (i < KAMA_GROUP_WIDTH) ctrl[i + cap] = tag;
}
/* Safe EMPTY deletion: every width-byte window containing i already has EMPTY.
 * Count the nonempty run on each side, excluding i; if shorter than width-1,
 * no previously full probe group is made empty. Works for either probe sequence. */
KAMA_FN int kama_can_erase_empty(const int8_t *ctrl, size_t cap, size_t i) {
    uint64_t before = kama_group_match(kama_group_load(ctrl + ((i - KAMA_GROUP_WIDTH) & (cap - 1))), KAMA_CTRL_EMPTY);
    uint64_t after = kama_group_match(kama_group_load(ctrl + i), KAMA_CTRL_EMPTY);
    if (!before || !after) return 0;
    return KAMA_GROUP_WIDTH - 1 - kama_mask_last(before) + kama_mask_first(after) < KAMA_GROUP_WIDTH;
}
KAMA_FN size_t kama_probe_next(size_t pos, size_t *stride, size_t mask) {
#if KAMA_LINEAR_PROBING
    (void)stride; return (pos + KAMA_GROUP_WIDTH) & mask;
#else
    *stride += KAMA_GROUP_WIDTH; return (pos + *stride) & mask;
#endif
}

/* Pinned upstream RapidHash V3; see vendor/rapidhash.json. */
/*
 * rapidhash V3 - Very fast, high quality, platform-independent hashing algorithm.
 *
 * Based on 'wyhash', by Wang Yi <godspeed_china@yeah.net>
 *
 * Copyright (C) 2025 Nicolas De Carli
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 * You can contact the author at:
 *   - rapidhash source repository: https://github.com/Nicoshev/rapidhash
 */



/*
 *  Includes.
 */
 #include <stdint.h>
 #include <string.h>
 #if defined(_MSC_VER)
 # include <intrin.h>
 # if defined(_M_X64) && !defined(_M_ARM64EC)
 #   pragma intrinsic(_umul128)
 # endif
 #endif

 /*
  *  C/C++ macros.
  */

 #ifdef _MSC_VER
 # define KAMA_RH_RAPIDHASH_ALWAYS_INLINE __forceinline
 #elif defined(__GNUC__)
 # define KAMA_RH_RAPIDHASH_ALWAYS_INLINE inline __attribute__((__always_inline__))
 #else
 # define KAMA_RH_RAPIDHASH_ALWAYS_INLINE inline
 #endif

 #ifdef __cplusplus
 # define KAMA_RH_RAPIDHASH_NOEXCEPT noexcept
 # define KAMA_RH_RAPIDHASH_CONSTEXPR constexpr
 # ifndef KAMA_RH_RAPIDHASH_INLINE
 #   define KAMA_RH_RAPIDHASH_INLINE KAMA_RH_RAPIDHASH_ALWAYS_INLINE
 # endif
 # if __cplusplus >= 201402L && !defined(_MSC_VER)
 #   define KAMA_RH_RAPIDHASH_INLINE_CONSTEXPR KAMA_RH_RAPIDHASH_ALWAYS_INLINE constexpr
 # else
 #   define KAMA_RH_RAPIDHASH_INLINE_CONSTEXPR KAMA_RH_RAPIDHASH_ALWAYS_INLINE
 # endif
 #else
 # define KAMA_RH_RAPIDHASH_NOEXCEPT
 # define KAMA_RH_RAPIDHASH_CONSTEXPR static const
 # ifndef KAMA_RH_RAPIDHASH_INLINE
 #   define KAMA_RH_RAPIDHASH_INLINE static KAMA_RH_RAPIDHASH_ALWAYS_INLINE
 # endif
 # define KAMA_RH_RAPIDHASH_INLINE_CONSTEXPR KAMA_RH_RAPIDHASH_INLINE
 #endif

 /*
  *  Unrolled macro.
  *  Improves large input speed, but increases code size and worsens small input speed.
  *
  *  RAPIDHASH_COMPACT: Normal behavior.
  *  RAPIDHASH_UNROLLED:
  *
  */
  #ifndef KAMA_RH_RAPIDHASH_UNROLLED
  # define KAMA_RH_RAPIDHASH_COMPACT
  #elif defined(KAMA_RH_RAPIDHASH_COMPACT)
  # error "cannot define RAPIDHASH_COMPACT and RAPIDHASH_UNROLLED simultaneously."
  #endif

 /*
  *  Protection macro, alters behaviour of rapid_mum multiplication function.
  *
  *  RAPIDHASH_FAST: Normal behavior, max speed.
  *  RAPIDHASH_PROTECTED: Extra protection against entropy loss.
  */
 #ifndef KAMA_RH_RAPIDHASH_PROTECTED
 # define KAMA_RH_RAPIDHASH_FAST
 #elif defined(KAMA_RH_RAPIDHASH_FAST)
 # error "cannot define RAPIDHASH_PROTECTED and RAPIDHASH_FAST simultaneously."
 #endif

 /*
  *  Likely and unlikely macros.
  */
 #if defined(__GNUC__) || defined(__INTEL_COMPILER) || defined(__clang__)
 # define KAMA_RH_LIKELY(x)  __builtin_expect(x,1)
 # define KAMA_RH_UNLIKELY(x)  __builtin_expect(x,0)
 #else
 # define KAMA_RH_LIKELY(x) (x)
 # define KAMA_RH_UNLIKELY(x) (x)
 #endif

 /*
  *  Endianness macros.
  */
 #ifndef KAMA_RH_RAPIDHASH_LITTLE_ENDIAN
 # if defined(_WIN32) || defined(__LITTLE_ENDIAN__) || (defined(__BYTE_ORDER__) && __BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__)
 #   define KAMA_RH_RAPIDHASH_LITTLE_ENDIAN
 # elif defined(__BIG_ENDIAN__) || (defined(__BYTE_ORDER__) && __BYTE_ORDER__ == __ORDER_BIG_ENDIAN__)
 #   define KAMA_RH_RAPIDHASH_BIG_ENDIAN
 # else
 #   warning "could not determine endianness! Falling back to little endian."
 #   define KAMA_RH_RAPIDHASH_LITTLE_ENDIAN
 # endif
 #endif

 /*
  *  Default secret parameters.
  */
   KAMA_RH_RAPIDHASH_CONSTEXPR uint64_t kama_rh_rapid_secret[8] = {
     0x2d358dccaa6c78a5ull,
     0x8bb84b93962eacc9ull,
     0x4b33a62ed433d4a3ull,
     0x4d5a2da51de1aa47ull,
     0xa0761d6478bd642full,
     0xe7037ed1a0b428dbull,
     0x90ed1765281c388cull,
     0xaaaaaaaaaaaaaaaaull};

 /*
  *  64*64 -> 128bit multiply function.
  *
  *  @param A  Address of 64-bit number.
  *  @param B  Address of 64-bit number.
  *
  *  Calculates 128-bit C = *A * *B.
  *
  *  When RAPIDHASH_FAST is defined:
  *  Overwrites A contents with C's low 64 bits.
  *  Overwrites B contents with C's high 64 bits.
  *
  *  When RAPIDHASH_PROTECTED is defined:
  *  Xors and overwrites A contents with C's low 64 bits.
  *  Xors and overwrites B contents with C's high 64 bits.
  */
 KAMA_RH_RAPIDHASH_INLINE_CONSTEXPR void kama_rh_rapid_mum(uint64_t *A, uint64_t *B) KAMA_RH_RAPIDHASH_NOEXCEPT {
 #if defined(__SIZEOF_INT128__)
   __uint128_t r=*A; r*=*B;
   #ifdef KAMA_RH_RAPIDHASH_PROTECTED
   *A^=(uint64_t)r; *B^=(uint64_t)(r>>64);
   #else
   *A=(uint64_t)r; *B=(uint64_t)(r>>64);
   #endif
 #elif defined(_MSC_VER) && (defined(_WIN64) || defined(_M_HYBRID_CHPE_ARM64))
   #if defined(_M_X64)
     #ifdef KAMA_RH_RAPIDHASH_PROTECTED
     uint64_t a, b;
     a=_umul128(*A,*B,&b);
     *A^=a;  *B^=b;
     #else
     *A=_umul128(*A,*B,B);
     #endif
   #else
     #ifdef KAMA_RH_RAPIDHASH_PROTECTED
     uint64_t a, b;
     b = __umulh(*A, *B);
     a = *A * *B;
     *A^=a;  *B^=b;
     #else
     uint64_t c = __umulh(*A, *B);
     *A = *A * *B;
     *B = c;
     #endif
   #endif
 #else
   uint64_t ha=*A>>32, hb=*B>>32, la=(uint32_t)*A, lb=(uint32_t)*B;
   uint64_t rh=ha*hb, rm0=ha*lb, rm1=hb*la, rl=la*lb, t=rl+(rm0<<32), c=t<rl;
   uint64_t lo=t+(rm1<<32);
   c+=lo<t;
   uint64_t hi=rh+(rm0>>32)+(rm1>>32)+c;
   #ifdef KAMA_RH_RAPIDHASH_PROTECTED
   *A^=lo;  *B^=hi;
   #else
   *A=lo;  *B=hi;
   #endif
 #endif
 }

 /*
  *  Multiply and xor mix function.
  *
  *  @param A  64-bit number.
  *  @param B  64-bit number.
  *
  *  Calculates 128-bit C = A * B.
  *  Returns 64-bit xor between high and low 64 bits of C.
  */
  KAMA_RH_RAPIDHASH_INLINE_CONSTEXPR uint64_t kama_rh_rapid_mix(uint64_t A, uint64_t B) KAMA_RH_RAPIDHASH_NOEXCEPT { kama_rh_rapid_mum(&A,&B); return A^B; }

 /*
  *  Read functions.
  */
 #ifdef KAMA_RH_RAPIDHASH_LITTLE_ENDIAN
 KAMA_RH_RAPIDHASH_INLINE uint64_t kama_rh_rapid_read64(const uint8_t *p) KAMA_RH_RAPIDHASH_NOEXCEPT { uint64_t v; memcpy(&v, p, sizeof(uint64_t)); return v;}
 KAMA_RH_RAPIDHASH_INLINE uint64_t kama_rh_rapid_read32(const uint8_t *p) KAMA_RH_RAPIDHASH_NOEXCEPT { uint32_t v; memcpy(&v, p, sizeof(uint32_t)); return v;}
 #elif defined(__GNUC__) || defined(__INTEL_COMPILER) || defined(__clang__)
 KAMA_RH_RAPIDHASH_INLINE uint64_t kama_rh_rapid_read64(const uint8_t *p) KAMA_RH_RAPIDHASH_NOEXCEPT { uint64_t v; memcpy(&v, p, sizeof(uint64_t)); return __builtin_bswap64(v);}
 KAMA_RH_RAPIDHASH_INLINE uint64_t kama_rh_rapid_read32(const uint8_t *p) KAMA_RH_RAPIDHASH_NOEXCEPT { uint32_t v; memcpy(&v, p, sizeof(uint32_t)); return __builtin_bswap32(v);}
 #elif defined(_MSC_VER)
 KAMA_RH_RAPIDHASH_INLINE uint64_t kama_rh_rapid_read64(const uint8_t *p) KAMA_RH_RAPIDHASH_NOEXCEPT { uint64_t v; memcpy(&v, p, sizeof(uint64_t)); return _byteswap_uint64(v);}
 KAMA_RH_RAPIDHASH_INLINE uint64_t kama_rh_rapid_read32(const uint8_t *p) KAMA_RH_RAPIDHASH_NOEXCEPT { uint32_t v; memcpy(&v, p, sizeof(uint32_t)); return _byteswap_ulong(v);}
 #else
 KAMA_RH_RAPIDHASH_INLINE uint64_t kama_rh_rapid_read64(const uint8_t *p) KAMA_RH_RAPIDHASH_NOEXCEPT {
   uint64_t v; memcpy(&v, p, 8);
   return (((v >> 56) & 0xff)| ((v >> 40) & 0xff00)| ((v >> 24) & 0xff0000)| ((v >>  8) & 0xff000000)| ((v <<  8) & 0xff00000000)| ((v << 24) & 0xff0000000000)| ((v << 40) & 0xff000000000000)| ((v << 56) & 0xff00000000000000));
 }
 KAMA_RH_RAPIDHASH_INLINE uint64_t kama_rh_rapid_read32(const uint8_t *p) KAMA_RH_RAPIDHASH_NOEXCEPT {
   uint32_t v; memcpy(&v, p, 4);
   return (((v >> 24) & 0xff)| ((v >>  8) & 0xff00)| ((v <<  8) & 0xff0000)| ((v << 24) & 0xff000000));
 }
 #endif

 /*
  *  rapidhash main function.
  *
  *  @param key     Buffer to be hashed.
  *  @param len     @key length, in bytes.
  *  @param seed    64-bit seed used to alter the hash result predictably.
  *  @param secret  Triplet of 64-bit secrets used to alter hash result predictably.
  *
  *  Returns a 64-bit hash.
  */
KAMA_RH_RAPIDHASH_INLINE_CONSTEXPR uint64_t kama_rh_rapidhash_internal(const void *key, size_t len, uint64_t seed, const uint64_t* secret) KAMA_RH_RAPIDHASH_NOEXCEPT {
  const uint8_t *p=(const uint8_t *)key;
  seed ^= kama_rh_rapid_mix(seed ^ secret[2], secret[1]);
  uint64_t a=0, b=0;
  size_t i = len;
  if (KAMA_RH_LIKELY(len <= 16)) {
    if (len >= 4) {
      seed ^= len;
      if (len >= 8) {
        const uint8_t* plast = p + len - 8;
        a = kama_rh_rapid_read64(p);
        b = kama_rh_rapid_read64(plast);
      } else {
        const uint8_t* plast = p + len - 4;
        a = kama_rh_rapid_read32(p);
        b = kama_rh_rapid_read32(plast);
      }
    } else if (len > 0) {
      a = (((uint64_t)p[0])<<45)|p[len-1];
      b = p[len>>1];
    } else
      a = b = 0;
  } else {
    if (len > 112) {
      uint64_t see1 = seed, see2 = seed;
      uint64_t see3 = seed, see4 = seed;
      uint64_t see5 = seed, see6 = seed;
#ifdef KAMA_RH_RAPIDHASH_COMPACT
      do {
        seed = kama_rh_rapid_mix(kama_rh_rapid_read64(p) ^ secret[0], kama_rh_rapid_read64(p + 8) ^ seed);
        see1 = kama_rh_rapid_mix(kama_rh_rapid_read64(p + 16) ^ secret[1], kama_rh_rapid_read64(p + 24) ^ see1);
        see2 = kama_rh_rapid_mix(kama_rh_rapid_read64(p + 32) ^ secret[2], kama_rh_rapid_read64(p + 40) ^ see2);
        see3 = kama_rh_rapid_mix(kama_rh_rapid_read64(p + 48) ^ secret[3], kama_rh_rapid_read64(p + 56) ^ see3);
        see4 = kama_rh_rapid_mix(kama_rh_rapid_read64(p + 64) ^ secret[4], kama_rh_rapid_read64(p + 72) ^ see4);
        see5 = kama_rh_rapid_mix(kama_rh_rapid_read64(p + 80) ^ secret[5], kama_rh_rapid_read64(p + 88) ^ see5);
        see6 = kama_rh_rapid_mix(kama_rh_rapid_read64(p + 96) ^ secret[6], kama_rh_rapid_read64(p + 104) ^ see6);
        p += 112;
        i -= 112;
      } while(i > 112);
#else
      while (i > 224) {
        seed = kama_rh_rapid_mix(kama_rh_rapid_read64(p) ^ secret[0], kama_rh_rapid_read64(p + 8) ^ seed);
        see1 = kama_rh_rapid_mix(kama_rh_rapid_read64(p + 16) ^ secret[1], kama_rh_rapid_read64(p + 24) ^ see1);
        see2 = kama_rh_rapid_mix(kama_rh_rapid_read64(p + 32) ^ secret[2], kama_rh_rapid_read64(p + 40) ^ see2);
        see3 = kama_rh_rapid_mix(kama_rh_rapid_read64(p + 48) ^ secret[3], kama_rh_rapid_read64(p + 56) ^ see3);
        see4 = kama_rh_rapid_mix(kama_rh_rapid_read64(p + 64) ^ secret[4], kama_rh_rapid_read64(p + 72) ^ see4);
        see5 = kama_rh_rapid_mix(kama_rh_rapid_read64(p + 80) ^ secret[5], kama_rh_rapid_read64(p + 88) ^ see5);
        see6 = kama_rh_rapid_mix(kama_rh_rapid_read64(p + 96) ^ secret[6], kama_rh_rapid_read64(p + 104) ^ see6);
        seed = kama_rh_rapid_mix(kama_rh_rapid_read64(p + 112) ^ secret[0], kama_rh_rapid_read64(p + 120) ^ seed);
        see1 = kama_rh_rapid_mix(kama_rh_rapid_read64(p + 128) ^ secret[1], kama_rh_rapid_read64(p + 136) ^ see1);
        see2 = kama_rh_rapid_mix(kama_rh_rapid_read64(p + 144) ^ secret[2], kama_rh_rapid_read64(p + 152) ^ see2);
        see3 = kama_rh_rapid_mix(kama_rh_rapid_read64(p + 160) ^ secret[3], kama_rh_rapid_read64(p + 168) ^ see3);
        see4 = kama_rh_rapid_mix(kama_rh_rapid_read64(p + 176) ^ secret[4], kama_rh_rapid_read64(p + 184) ^ see4);
        see5 = kama_rh_rapid_mix(kama_rh_rapid_read64(p + 192) ^ secret[5], kama_rh_rapid_read64(p + 200) ^ see5);
        see6 = kama_rh_rapid_mix(kama_rh_rapid_read64(p + 208) ^ secret[6], kama_rh_rapid_read64(p + 216) ^ see6);
        p += 224;
        i -= 224;
      }
      if (i > 112) {
        seed = kama_rh_rapid_mix(kama_rh_rapid_read64(p) ^ secret[0], kama_rh_rapid_read64(p + 8) ^ seed);
        see1 = kama_rh_rapid_mix(kama_rh_rapid_read64(p + 16) ^ secret[1], kama_rh_rapid_read64(p + 24) ^ see1);
        see2 = kama_rh_rapid_mix(kama_rh_rapid_read64(p + 32) ^ secret[2], kama_rh_rapid_read64(p + 40) ^ see2);
        see3 = kama_rh_rapid_mix(kama_rh_rapid_read64(p + 48) ^ secret[3], kama_rh_rapid_read64(p + 56) ^ see3);
        see4 = kama_rh_rapid_mix(kama_rh_rapid_read64(p + 64) ^ secret[4], kama_rh_rapid_read64(p + 72) ^ see4);
        see5 = kama_rh_rapid_mix(kama_rh_rapid_read64(p + 80) ^ secret[5], kama_rh_rapid_read64(p + 88) ^ see5);
        see6 = kama_rh_rapid_mix(kama_rh_rapid_read64(p + 96) ^ secret[6], kama_rh_rapid_read64(p + 104) ^ see6);
        p += 112;
        i -= 112;
      }
#endif
      seed ^= see1;
      see2 ^= see3;
      see4 ^= see5;
      seed ^= see6;
      see2 ^= see4;
      seed ^= see2;
    }
    if (i > 16) {
      seed = kama_rh_rapid_mix(kama_rh_rapid_read64(p) ^ secret[2], kama_rh_rapid_read64(p + 8) ^ seed);
      if (i > 32) {
          seed = kama_rh_rapid_mix(kama_rh_rapid_read64(p + 16) ^ secret[2], kama_rh_rapid_read64(p + 24) ^ seed);
          if (i > 48) {
              seed = kama_rh_rapid_mix(kama_rh_rapid_read64(p + 32) ^ secret[1], kama_rh_rapid_read64(p + 40) ^ seed);
              if (i > 64) {
                  seed = kama_rh_rapid_mix(kama_rh_rapid_read64(p + 48) ^ secret[1], kama_rh_rapid_read64(p + 56) ^ seed);
                  if (i > 80) {
                      seed = kama_rh_rapid_mix(kama_rh_rapid_read64(p + 64) ^ secret[2], kama_rh_rapid_read64(p + 72) ^ seed);
                      if (i > 96) {
                          seed = kama_rh_rapid_mix(kama_rh_rapid_read64(p + 80) ^ secret[1], kama_rh_rapid_read64(p + 88) ^ seed);
                      }
                  }
              }
          }
      }
    }
    a=kama_rh_rapid_read64(p+i-16) ^ i;  b=kama_rh_rapid_read64(p+i-8);
  }
  a ^= secret[1];
  b ^= seed;
  kama_rh_rapid_mum(&a, &b);
  return kama_rh_rapid_mix(a ^ secret[7], b ^ secret[1] ^ i);
}

 /*
  *  rapidhashMicro main function.
  *
  *  @param key     Buffer to be hashed.
  *  @param len     @key length, in bytes.
  *  @param seed    64-bit seed used to alter the hash result predictably.
  *  @param secret  Triplet of 64-bit secrets used to alter hash result predictably.
  *
  *  Returns a 64-bit hash.
  */
  KAMA_RH_RAPIDHASH_INLINE_CONSTEXPR uint64_t kama_rh_rapidhashMicro_internal(const void *key, size_t len, uint64_t seed, const uint64_t* secret) KAMA_RH_RAPIDHASH_NOEXCEPT {
    const uint8_t *p=(const uint8_t *)key;
    seed ^= kama_rh_rapid_mix(seed ^ secret[2], secret[1]);
    uint64_t a=0, b=0;
    size_t i = len;
    if (KAMA_RH_LIKELY(len <= 16)) {
      if (len >= 4) {
        seed ^= len;
        if (len >= 8) {
          const uint8_t* plast = p + len - 8;
          a = kama_rh_rapid_read64(p);
          b = kama_rh_rapid_read64(plast);
        } else {
          const uint8_t* plast = p + len - 4;
          a = kama_rh_rapid_read32(p);
          b = kama_rh_rapid_read32(plast);
        }
      } else if (len > 0) {
        a = (((uint64_t)p[0])<<45)|p[len-1];
        b = p[len>>1];
      } else
        a = b = 0;
    } else {
      if (i > 80) {
        uint64_t see1 = seed, see2 = seed;
        uint64_t see3 = seed, see4 = seed;
        do {
          seed = kama_rh_rapid_mix(kama_rh_rapid_read64(p) ^ secret[0], kama_rh_rapid_read64(p + 8) ^ seed);
          see1 = kama_rh_rapid_mix(kama_rh_rapid_read64(p + 16) ^ secret[1], kama_rh_rapid_read64(p + 24) ^ see1);
          see2 = kama_rh_rapid_mix(kama_rh_rapid_read64(p + 32) ^ secret[2], kama_rh_rapid_read64(p + 40) ^ see2);
          see3 = kama_rh_rapid_mix(kama_rh_rapid_read64(p + 48) ^ secret[3], kama_rh_rapid_read64(p + 56) ^ see3);
          see4 = kama_rh_rapid_mix(kama_rh_rapid_read64(p + 64) ^ secret[4], kama_rh_rapid_read64(p + 72) ^ see4);
          p += 80;
          i -= 80;
        } while(i > 80);
        seed ^= see1;
        see2 ^= see3;
        seed ^= see4;
        seed ^= see2;
      }
      if (i > 16) {
        seed = kama_rh_rapid_mix(kama_rh_rapid_read64(p) ^ secret[2], kama_rh_rapid_read64(p + 8) ^ seed);
        if (i > 32) {
            seed = kama_rh_rapid_mix(kama_rh_rapid_read64(p + 16) ^ secret[2], kama_rh_rapid_read64(p + 24) ^ seed);
            if (i > 48) {
                seed = kama_rh_rapid_mix(kama_rh_rapid_read64(p + 32) ^ secret[1], kama_rh_rapid_read64(p + 40) ^ seed);
                if (i > 64) {
                    seed = kama_rh_rapid_mix(kama_rh_rapid_read64(p + 48) ^ secret[1], kama_rh_rapid_read64(p + 56) ^ seed);
                }
            }
        }
      }
      a=kama_rh_rapid_read64(p+i-16) ^ i;  b=kama_rh_rapid_read64(p+i-8);
    }
    a ^= secret[1];
    b ^= seed;
    kama_rh_rapid_mum(&a, &b);
    return kama_rh_rapid_mix(a ^ secret[7], b ^ secret[1] ^ i);
  }

  /*
  *  rapidhashNano main function.
  *
  *  @param key     Buffer to be hashed.
  *  @param len     @key length, in bytes.
  *  @param seed    64-bit seed used to alter the hash result predictably.
  *  @param secret  Triplet of 64-bit secrets used to alter hash result predictably.
  *
  *  Returns a 64-bit hash.
  */
  KAMA_RH_RAPIDHASH_INLINE_CONSTEXPR uint64_t kama_rh_rapidhashNano_internal(const void *key, size_t len, uint64_t seed, const uint64_t* secret) KAMA_RH_RAPIDHASH_NOEXCEPT {
    const uint8_t *p=(const uint8_t *)key;
    seed ^= kama_rh_rapid_mix(seed ^ secret[2], secret[1]);
    uint64_t a=0, b=0;
    size_t i = len;
    if (KAMA_RH_LIKELY(len <= 16)) {
      if (len >= 4) {
        seed ^= len;
        if (len >= 8) {
          const uint8_t* plast = p + len - 8;
          a = kama_rh_rapid_read64(p);
          b = kama_rh_rapid_read64(plast);
        } else {
          const uint8_t* plast = p + len - 4;
          a = kama_rh_rapid_read32(p);
          b = kama_rh_rapid_read32(plast);
        }
      } else if (len > 0) {
        a = (((uint64_t)p[0])<<45)|p[len-1];
        b = p[len>>1];
      } else
        a = b = 0;
    } else {
      if (i > 48) {
        uint64_t see1 = seed, see2 = seed;
        do {
          seed = kama_rh_rapid_mix(kama_rh_rapid_read64(p) ^ secret[0], kama_rh_rapid_read64(p + 8) ^ seed);
          see1 = kama_rh_rapid_mix(kama_rh_rapid_read64(p + 16) ^ secret[1], kama_rh_rapid_read64(p + 24) ^ see1);
          see2 = kama_rh_rapid_mix(kama_rh_rapid_read64(p + 32) ^ secret[2], kama_rh_rapid_read64(p + 40) ^ see2);
          p += 48;
          i -= 48;
        } while(i > 48);
        seed ^= see1;
        seed ^= see2;
      }
      if (i > 16) {
        seed = kama_rh_rapid_mix(kama_rh_rapid_read64(p) ^ secret[2], kama_rh_rapid_read64(p + 8) ^ seed);
        if (i > 32) {
            seed = kama_rh_rapid_mix(kama_rh_rapid_read64(p + 16) ^ secret[2], kama_rh_rapid_read64(p + 24) ^ seed);
        }
      }
      a=kama_rh_rapid_read64(p+i-16) ^ i;  b=kama_rh_rapid_read64(p+i-8);
    }
    a ^= secret[1];
    b ^= seed;
    kama_rh_rapid_mum(&a, &b);
    return kama_rh_rapid_mix(a ^ secret[7], b ^ secret[1] ^ i);
  }

/*
 *  rapidhash seeded hash function.
 *
 *  @param key     Buffer to be hashed.
 *  @param len     @key length, in bytes.
 *  @param seed    64-bit seed used to alter the hash result predictably.
 *
 *  Calls rapidhash_internal using provided parameters and default secrets.
 *
 *  Returns a 64-bit hash.
 */
KAMA_RH_RAPIDHASH_INLINE_CONSTEXPR uint64_t kama_rh_rapidhash_withSeed(const void *key, size_t len, uint64_t seed) KAMA_RH_RAPIDHASH_NOEXCEPT {
  return kama_rh_rapidhash_internal(key, len, seed, kama_rh_rapid_secret);
}

/*
 *  rapidhash general purpose hash function.
 *
 *  @param key     Buffer to be hashed.
 *  @param len     @key length, in bytes.
 *
 *  Calls rapidhash_withSeed using provided parameters and the default seed.
 *
 *  Returns a 64-bit hash.
 */
KAMA_RH_RAPIDHASH_INLINE_CONSTEXPR uint64_t kama_rh_rapidhash(const void *key, size_t len) KAMA_RH_RAPIDHASH_NOEXCEPT {
  return kama_rh_rapidhash_withSeed(key, len, 0);
}

/*
 *  rapidhashMicro seeded hash function.
 *
 *  Designed for HPC and server applications, where cache misses make a noticeable performance detriment.
 *  Clang-18+ compiles it to ~140 instructions without stack usage, both on x86-64 and aarch64.
 *  Faster for sizes up to 512 bytes, just 15%-20% slower for inputs above 1kb.
 *
 *  @param key     Buffer to be hashed.
 *  @param len     @key length, in bytes.
 *  @param seed    64-bit seed used to alter the hash result predictably.
 *
 *  Calls rapidhash_internal using provided parameters and default secrets.
 *
 *  Returns a 64-bit hash.
 */
 KAMA_RH_RAPIDHASH_INLINE_CONSTEXPR uint64_t kama_rh_rapidhashMicro_withSeed(const void *key, size_t len, uint64_t seed) KAMA_RH_RAPIDHASH_NOEXCEPT {
  return kama_rh_rapidhashMicro_internal(key, len, seed, kama_rh_rapid_secret);
}

/*
 *  rapidhashMicro hash function.
 *
 *  @param key     Buffer to be hashed.
 *  @param len     @key length, in bytes.
 *
 *  Calls rapidhash_withSeed using provided parameters and the default seed.
 *
 *  Returns a 64-bit hash.
 */
KAMA_RH_RAPIDHASH_INLINE_CONSTEXPR uint64_t kama_rh_rapidhashMicro(const void *key, size_t len) KAMA_RH_RAPIDHASH_NOEXCEPT {
  return kama_rh_rapidhashMicro_withSeed(key, len, 0);
}

/*
 *  rapidhashNano seeded hash function.
 *
 *  @param key     Buffer to be hashed.
 *  @param len     @key length, in bytes.
 *  @param seed    64-bit seed used to alter the hash result predictably.
 *
 *  Calls rapidhash_internal using provided parameters and default secrets.
 *
 *  Returns a 64-bit hash.
 */
 KAMA_RH_RAPIDHASH_INLINE_CONSTEXPR uint64_t kama_rh_rapidhashNano_withSeed(const void *key, size_t len, uint64_t seed) KAMA_RH_RAPIDHASH_NOEXCEPT {
  return kama_rh_rapidhashNano_internal(key, len, seed, kama_rh_rapid_secret);
}

/*
 *  rapidhashNano hash function.
 *
 *  Designed for Mobile and embedded applications, where keeping a small code size is a top priority.
 *  Clang-18+ compiles it to less than 100 instructions without stack usage, both on x86-64 and aarch64.
 *  The fastest for sizes up to 48 bytes, but may be considerably slower for larger inputs.
 *
 *  @param key     Buffer to be hashed.
 *  @param len     @key length, in bytes.
 *
 *  Calls rapidhash_withSeed using provided parameters and the default seed.
 *
 *  Returns a 64-bit hash.
 */
KAMA_RH_RAPIDHASH_INLINE_CONSTEXPR uint64_t kama_rh_rapidhashNano(const void *key, size_t len) KAMA_RH_RAPIDHASH_NOEXCEPT {
  return kama_rh_rapidhashNano_withSeed(key, len, 0);
}

KAMA_FN uint64_t kama_rapidhash(const char *p, size_t len, uint64_t seed) {
    return kama_rh_rapidhash_withSeed(p, len, seed);
}
/* Hoist upstream's seed-only multiplication out of repeated short-key hashes.
 * XOR with the seed-zero preparation keeps a zero-initialized map usable. */
KAMA_HOT uint64_t kama_prepare_hash_seed(uint64_t seed) {
    return seed ^ kama_rh_rapid_mix(seed ^ kama_rh_rapid_secret[2], kama_rh_rapid_secret[1]);
}
KAMA_HOT uint64_t kama_hash_short(const char *key, size_t len, uint64_t prepared_seed) {
    const uint8_t *p=(const uint8_t *)key;
    uint64_t a=0,b=0;
    if(len>=4) {
        prepared_seed^=len;
        if(len>=8) {a=kama_rh_rapid_read64(p);b=kama_rh_rapid_read64(p+len-8);}
        else {a=kama_rh_rapid_read32(p);b=kama_rh_rapid_read32(p+len-4);}
    } else if(len) {a=((uint64_t)p[0]<<45)|p[len-1];b=p[len/2];}
    a^=kama_rh_rapid_secret[1];b^=prepared_seed;
    kama_rh_rapid_mum(&a,&b);
    return kama_rh_rapid_mix(a^kama_rh_rapid_secret[7],b^kama_rh_rapid_secret[1]^len);
}
KAMA_FN uint64_t kama_hash_u64(uint64_t x) {
    x ^= x >> 30; x *= UINT64_C(0xbf58476d1ce4e5b9);
    x ^= x >> 27; x *= UINT64_C(0x94d049bb133111eb);
    return x ^ (x >> 31);
}
KAMA_FN uint32_t kama_hash_u32(uint32_t x) {
    x ^= x >> 16; x *= UINT32_C(0x7feb352d);
    x ^= x >> 15; x *= UINT32_C(0x846ca68b);
    return x ^ (x >> 16);
}
KAMA_FN uint64_t kama_hash_integer32(uint32_t x, uint64_t seed) {
    uint32_t h = kama_hash_u32(x ^ (uint32_t)seed ^ (uint32_t)(seed >> 32));
    return h | ((uint64_t)h << 32);
}
KAMA_FN int kama_key_eq(const char *a, const char *b, size_t len) {
    if (a == b || !len) return 1;
    if (len == 16) return kama_read_le64(a) == kama_read_le64(b) && kama_read_le64(a+8) == kama_read_le64(b+8);
    return memcmp(a, b, len) == 0;
}
KAMA_FN const char *kama_backend_name(void) {
#if defined(KAMA_SIMD_AVX512)
    return "avx512bw";
#elif defined(KAMA_SIMD_AVX)
    return "avx2";
#elif defined(KAMA_SIMD_SSE)
    return "sse2";
#elif defined(KAMA_SIMD_NEON)
    return "neon";
#else
    return "scalar-swar";
#endif
}

/* Optional keyed hash hook: SipHash-2-4. Caller supplies a secret 128-bit key.
 * Algorithm: Aumasson/Bernstein, https://www.aumasson.jp/siphash/ . */
typedef struct { uint64_t k0, k1; } kama_siphash_key_t;
KAMA_FN uint64_t kama_rotate64(uint64_t x, unsigned n) { return (x << n) | (x >> (64 - n)); }
#define KAMA_SIPROUND() do { \
    v0 += v1; v1 = kama_rotate64(v1, 13); v1 ^= v0; v0 = kama_rotate64(v0, 32); \
    v2 += v3; v3 = kama_rotate64(v3, 16); v3 ^= v2; \
    v0 += v3; v3 = kama_rotate64(v3, 21); v3 ^= v0; \
    v2 += v1; v1 = kama_rotate64(v1, 17); v1 ^= v2; v2 = kama_rotate64(v2, 32); \
} while (0)
KAMA_FN uint64_t kama_siphash24(const void *data, size_t len, uint64_t seed, void *context) {
    const kama_siphash_key_t *key = (const kama_siphash_key_t *)context;
    const unsigned char *p = (const unsigned char *)data;
    uint64_t k0 = key->k0 ^ seed, k1 = key->k1;
    uint64_t v0 = UINT64_C(0x736f6d6570736575) ^ k0, v1 = UINT64_C(0x646f72616e646f6d) ^ k1;
    uint64_t v2 = UINT64_C(0x6c7967656e657261) ^ k0, v3 = UINT64_C(0x7465646279746573) ^ k1;
    size_t n = len;
    while (n >= 8) {
        uint64_t m = kama_read_le64(p); v3 ^= m; KAMA_SIPROUND(); KAMA_SIPROUND(); v0 ^= m;
        p += 8; n -= 8;
    }
    uint64_t b = (uint64_t)len << 56;
    for (size_t i = 0; i < n; ++i) b |= (uint64_t)p[i] << (8 * i);
    v3 ^= b; KAMA_SIPROUND(); KAMA_SIPROUND(); v0 ^= b; v2 ^= 0xff;
    KAMA_SIPROUND(); KAMA_SIPROUND(); KAMA_SIPROUND(); KAMA_SIPROUND();
    return v0 ^ v1 ^ v2 ^ v3;
}
#undef KAMA_SIPROUND

#define KAMA_DECLARE(NAME, KEYARG, KEYSTORE, META, META_BYTES, PACKED, VALUE_MEMBER) \
typedef KEYARG NAME##_keyarg_t; \
typedef KEYSTORE NAME##_storage_t; \
typedef META NAME##_meta_t; \
enum { NAME##_meta_bytes = META_BYTES }; \
enum { NAME##_packed = PACKED }; \
typedef struct { NAME##_storage_t key; VALUE_MEMBER } NAME##_pair_t; \
typedef struct { \
    int8_t *ctrl; \
    NAME##_meta_t *meta; \
    NAME##_pair_t *slots; \
    void *heap; \
    size_t size, capacity, resize_threshold, tombstones; \
    size_t heap_bytes, key_bytes; \
    uint64_t hash_seed_delta; \
    kama_options_t options; \
} NAME##_t; \
typedef struct { size_t index; int found; } NAME##_location_t; \

#define KAMA_STRING(NAME, METADATA) \
KAMA_HOT kama_meta_t *NAME##_metadata(const NAME##_t *map, size_t i) { return METADATA; } \
typedef struct { unsigned char bytes[16]; } NAME##_staging_t; \
KAMA_FN int NAME##_valid_key(NAME##_keyarg_t key) { \
    return key.len <= UINT32_MAX && (key.data || key.len == 0); \
} \
KAMA_FN void NAME##_stabilize_arg(NAME##_keyarg_t *arg, NAME##_staging_t *storage) { \
    if (arg->len <= 8 || (NAME##_packed && arg->len == 16)) { \
        memset(storage, 0, sizeof(*storage)); \
        if (arg->len) memcpy(storage->bytes, arg->data, arg->len); \
        arg->data = (const char *)storage->bytes; \
    } \
} \
KAMA_HOT uint64_t NAME##_hash_arg(const NAME##_t *map, NAME##_keyarg_t key) { \
    const char *p = key.data ? key.data : ""; \
    if (map->options.hash) return map->options.hash(p, key.len, map->options.seed, map->options.key_context); \
    if (key.len <= 16) return kama_hash_short(p, key.len, map->hash_seed_delta ^ kama_prepare_hash_seed(0)); \
    return kama_rapidhash(p, key.len, map->options.seed); \
} \
KAMA_FN const char *NAME##_key(const NAME##_t *map, size_t i) { \
    if (NAME##_packed && kama_is_inline16(map->ctrl, map->capacity, i)) \
        return (const char *)&map->slots[i]; \
    return NAME##_metadata(map, i)[0].len <= 8 ? (const char *)&map->slots[i].key.inline_key : map->slots[i].key.ptr; \
} \
KAMA_FN size_t NAME##_key_len(const NAME##_t *map, size_t i) { \
    return NAME##_packed && kama_is_inline16(map->ctrl, map->capacity, i) ? 16 : NAME##_metadata(map, i)[0].len; \
} \
KAMA_HOT int NAME##_equal_slot(const NAME##_t *map, size_t i, NAME##_keyarg_t key, uint64_t hash) { \
    if (NAME##_packed && key.len == 16) { \
        if (!kama_is_inline16(map->ctrl, map->capacity, i)) return 0; \
        KAMA_STAT(map, key_comparisons, 1); \
        return map->options.equal \
            ? map->options.equal(&map->slots[i], key.data, 16, map->options.key_context) \
            : kama_key_eq((const char *)&map->slots[i], key.data, 16); \
    } \
    if (NAME##_metadata(map, i)[0].hash != (uint32_t)hash || NAME##_metadata(map, i)[0].len != key.len) return 0; \
    if (NAME##_packed && kama_is_inline16(map->ctrl, map->capacity, i)) return 0; \
    KAMA_STAT(map, key_comparisons, 1); \
    if (map->options.equal) \
        return map->options.equal(NAME##_key(map, i), key.data ? key.data : "", key.len, map->options.key_context); \
    if (key.len <= 8) { \
        uint64_t bits = 0; if (key.len) memcpy(&bits, key.data, key.len); \
        return bits == map->slots[i].key.inline_key; \
    } \
    return kama_key_eq(map->slots[i].key.ptr, key.data, key.len); \
} \
KAMA_FN int NAME##_store_key(NAME##_t *map, size_t i, NAME##_keyarg_t key, uint64_t hash) { \
    if (NAME##_packed) { \
        kama_set_inline16(map->ctrl, map->capacity, i, key.len == 16); \
        if (key.len == 16) { memcpy(&map->slots[i], key.data, 16); return 1; } \
    } \
    if (key.len <= 8) { \
        map->slots[i].key.inline_key = 0; \
        if (key.len) memcpy(&map->slots[i].key.inline_key, key.data, key.len); \
    } else if (map->options.copy_keys) { \
        size_t bytes; \
        if (!kama_add_size(key.len, 1, &bytes)) return 0; \
        char *p = (char *)kama_allocate(&map->options, bytes, sizeof(void *)); \
        if (!p) return 0; \
        memcpy(p, key.data, key.len); p[key.len] = 0; \
        map->slots[i].key.ptr = p; map->key_bytes += bytes; \
    } else map->slots[i].key.ptr = key.data; \
    NAME##_metadata(map, i)[0].hash = (uint32_t)hash; NAME##_metadata(map, i)[0].len = (uint32_t)key.len; \
    return 1; \
} \
KAMA_FN void NAME##_drop_key(NAME##_t *map, size_t i) { \
    if (map->options.copy_keys && !(NAME##_packed && kama_is_inline16(map->ctrl, map->capacity, i)) && NAME##_metadata(map, i)[0].len > 8) { \
        size_t bytes = (size_t)NAME##_metadata(map, i)[0].len + 1; \
        kama_deallocate(&map->options, (void *)map->slots[i].key.ptr, bytes, sizeof(void *)); \
        map->key_bytes -= bytes; \
    } \
} \
KAMA_FN uint64_t NAME##_slot_hash(const NAME##_t *map, size_t i) { \
    if (NAME##_packed && kama_is_inline16(map->ctrl, map->capacity, i)) { \
        NAME##_keyarg_t key = {(const char *)&map->slots[i], 16}; \
        return NAME##_hash_arg(map, key); \
    } \
    return NAME##_metadata(map, i)[0].hash | ((uint64_t)(uint8_t)map->ctrl[i] << 57); \
} \

#define KAMA_FIXED(NAME, VALID, ARG_BYTES, DEFAULT_HASH, EXPORT_TYPE, EXPORT, DEFAULT_EQUAL, SLOT_ARG, STABLE_ARG) \
typedef NAME##_storage_t NAME##_staging_t; \
KAMA_FN int NAME##_valid_key(NAME##_keyarg_t key) { (void)key; return VALID; } \
KAMA_FN void NAME##_stabilize_arg(NAME##_keyarg_t *arg, NAME##_storage_t *storage) { \
    NAME##_keyarg_t key = *arg; \
    memcpy(storage, ARG_BYTES, sizeof(*storage)); *arg = STABLE_ARG; \
} \
KAMA_HOT uint64_t NAME##_hash_arg(const NAME##_t *map, NAME##_keyarg_t key) { \
    return map->options.hash ? map->options.hash(ARG_BYTES, sizeof(NAME##_storage_t), map->options.seed, map->options.key_context) \
                             : DEFAULT_HASH; \
} \
KAMA_FN EXPORT_TYPE NAME##_key(const NAME##_t *map, size_t i) { return EXPORT; } \
KAMA_FN size_t NAME##_key_len(const NAME##_t *map, size_t i) { (void)map; (void)i; return sizeof(NAME##_storage_t); } \
KAMA_HOT int NAME##_equal_slot(const NAME##_t *map, size_t i, NAME##_keyarg_t key, uint64_t hash) { \
    (void)hash; KAMA_STAT(map, key_comparisons, 1); \
    return map->options.equal ? map->options.equal(&map->slots[i].key, ARG_BYTES, sizeof(NAME##_storage_t), map->options.key_context) \
                              : DEFAULT_EQUAL; \
} \
KAMA_FN int NAME##_store_key(NAME##_t *map, size_t i, NAME##_keyarg_t key, uint64_t hash) { \
    (void)hash; memcpy(&map->slots[i].key, ARG_BYTES, sizeof(NAME##_storage_t)); return 1; \
} \
KAMA_FN void NAME##_drop_key(NAME##_t *map, size_t i) { (void)map; (void)i; } \
KAMA_FN uint64_t NAME##_slot_hash(const NAME##_t *map, size_t i) { \
    NAME##_keyarg_t key = SLOT_ARG; \
    return NAME##_hash_arg(map, key); \
} \

#define KAMA_TABLE(NAME) \
KAMA_FN size_t NAME##_alignment(void) { \
    size_t a = KAMA_ALIGNOF(NAME##_pair_t); return a > 32 ? a : 32; \
} \
KAMA_FN size_t NAME##_allocated_bytes(const NAME##_t *map) { return map->heap_bytes + map->key_bytes; } \
KAMA_FN size_t NAME##_count(const NAME##_t *map) { return map->size; } \
KAMA_FN int NAME##_empty(const NAME##_t *map) { return map->size == 0; } \
KAMA_FN int NAME##_allocate_table(NAME##_t *map, size_t cap) { \
    size_t metadata, data, offset, bytes, alignment = NAME##_alignment(); \
    if (!kama_round_capacity(cap, &cap) || \
        !kama_mul_size(cap, NAME##_meta_bytes, &metadata) || \
        !kama_add_size(metadata, alignment - 1, &offset)) return 0; \
    offset &= ~(alignment - 1); \
    if (!kama_mul_size(cap, sizeof(NAME##_pair_t), &data) || \
        !kama_add_size(offset, data, &bytes) || \
        !kama_add_size(bytes, cap, &bytes) || \
        !kama_add_size(bytes, KAMA_GROUP_WIDTH, &bytes) || \
        !kama_add_size(bytes, NAME##_packed ? cap / 8 : 0, &bytes)) return 0; \
    void *heap = kama_allocate(&map->options, bytes, alignment); \
    if (!heap) return 0; \
    map->heap = heap; map->heap_bytes = bytes; \
    map->meta = NAME##_meta_bytes != 0 ? (NAME##_meta_t *)heap : NULL; \
    map->slots = (NAME##_pair_t *)((uint8_t *)heap + offset); \
    map->ctrl = (int8_t *)((uint8_t *)heap + offset + data); \
    memset(map->ctrl, KAMA_CTRL_EMPTY, cap + KAMA_GROUP_WIDTH); \
    if (NAME##_packed) memset(map->ctrl + cap + KAMA_GROUP_WIDTH, 0, cap / 8); \
    map->capacity = cap; map->resize_threshold = kama_threshold(cap); \
    return 1; \
} \
KAMA_FN int NAME##_init_ex(NAME##_t *map, size_t cap, const kama_options_t *options) { \
    kama_options_t chosen; \
    memset(&chosen, 0, sizeof(chosen)); chosen.seed = KAMA_SEED; \
    if (options) chosen = *options; \
    memset(map, 0, sizeof(*map)); \
    if (!!chosen.allocate != !!chosen.deallocate) return 0; \
    map->options = chosen; \
    map->hash_seed_delta = kama_prepare_hash_seed(chosen.seed) ^ kama_prepare_hash_seed(0); \
    return cap == 0 || NAME##_allocate_table(map, cap); \
} \
KAMA_FN int NAME##_init(NAME##_t *map, size_t cap) { return NAME##_init_ex(map, cap, NULL); } \
KAMA_FN void NAME##_clear(NAME##_t *map) { \
    if (map->options.copy_keys) \
        for (size_t i = 0; i < map->capacity; ++i) if (map->ctrl[i] >= 0) NAME##_drop_key(map, i); \
    if (map->ctrl) memset(map->ctrl, KAMA_CTRL_EMPTY, map->capacity + KAMA_GROUP_WIDTH); \
    map->size = 0; map->tombstones = 0; \
} \
KAMA_FN void NAME##_free(NAME##_t *map) { \
    NAME##_clear(map); \
    kama_deallocate(&map->options, map->heap, map->heap_bytes, NAME##_alignment()); \
    memset(map, 0, sizeof(*map)); \
} \
KAMA_HOT NAME##_location_t NAME##_locate(const NAME##_t *map, NAME##_keyarg_t key, uint64_t hash, int inserting) { \
    NAME##_location_t result = {map->capacity, 0}; \
    if (!map->capacity) return result; \
    size_t mask = map->capacity - 1, pos = (uint32_t)hash & mask, stride = 0; \
    if (KAMA_LOOKUP_PREFETCH) KAMA_PREFETCH(map->ctrl + pos); \
    if (KAMA_LOOKUP_PREFETCH > 1) { \
        if (NAME##_meta_bytes != 0) KAMA_PREFETCH(map->meta + pos); \
        else KAMA_PREFETCH(map->slots + pos); \
    } \
    /* The occupancy budget always leaves EMPTY, and either probe sequence \
     * visits every group. Avoid a redundant counter on the hot path. */ \
    for (;;) { \
        KAMA_STAT(map, probe_groups, 1); \
        kama_group_t group = kama_group_load(map->ctrl + pos); \
        if (inserting != 2) { \
            uint64_t matches = kama_group_match(group, KAMA_H2(hash)); \
            while (matches) { \
                size_t i = (pos + kama_mask_first(matches)) & mask; \
                if (NAME##_equal_slot(map, i, key, hash)) { result.index = i; result.found = 1; return result; } \
                matches &= matches - 1; \
            } \
        } \
        if (inserting && result.index == map->capacity) { \
            uint64_t available = kama_group_available(group); \
            if (available) result.index = (pos + kama_mask_first(available)) & mask; \
        } \
        if (kama_group_match(group, KAMA_CTRL_EMPTY)) return result; \
        pos = kama_probe_next(pos, &stride, mask); \
    } \
    return result; \
} \
KAMA_FN int NAME##_rehash(NAME##_t *map, size_t requested) { \
    size_t cap, minimum; \
    if (!kama_capacity_for(map->size, &minimum) || !kama_round_capacity(requested, &cap)) return 0; \
    if (cap < minimum) cap = minimum; \
    NAME##_t next; memset(&next, 0, sizeof(next)); next.options = map->options; \
    next.hash_seed_delta = map->hash_seed_delta; \
    if (!NAME##_allocate_table(&next, cap)) return 0; \
    for (size_t i = 0; i < map->capacity; ++i) { \
        if (map->ctrl[i] < 0) continue; \
        uint64_t hash = NAME##_slot_hash(map, i); \
        size_t mask = cap - 1, pos = (uint32_t)hash & mask, stride = 0; \
        for (;;) { \
            uint64_t available = kama_group_available(kama_group_load(next.ctrl + pos)); \
            if (available) { \
                size_t ins = (pos + kama_mask_first(available)) & mask; \
                next.slots[ins] = map->slots[i]; \
                if (NAME##_packed) kama_set_inline16(next.ctrl, cap, ins, kama_is_inline16(map->ctrl, map->capacity, i)); \
                if (NAME##_meta_bytes != 0) memcpy((uint8_t *)next.meta + ins * NAME##_meta_bytes, \
                                              (const uint8_t *)map->meta + i * NAME##_meta_bytes, NAME##_meta_bytes); \
                kama_set_ctrl(next.ctrl, cap, ins, map->ctrl[i]); \
                break; \
            } \
            pos = kama_probe_next(pos, &stride, mask); \
        } \
    } \
    next.size = map->size; next.key_bytes = map->key_bytes; \
    KAMA_STAT(map, rehashes, 1); KAMA_STAT(map, migrated_entries, map->size); \
    kama_deallocate(&map->options, map->heap, map->heap_bytes, NAME##_alignment()); \
    *map = next; return 1; \
} \
KAMA_FN int NAME##_resize(NAME##_t *map, size_t cap) { return NAME##_rehash(map, cap); } \
KAMA_FN int NAME##_reserve_entries(NAME##_t *map, size_t entries) { \
    size_t cap; \
    if (entries < map->size) entries = map->size; \
    if (entries <= map->resize_threshold) \
        return map->tombstones <= map->resize_threshold - entries || NAME##_rehash(map, map->capacity); \
    if (!kama_capacity_for(entries, &cap)) return 0; \
    return NAME##_rehash(map, cap); \
} \
KAMA_FN int NAME##_compact(NAME##_t *map) { return !map->tombstones || NAME##_rehash(map, map->capacity); } \
KAMA_FN int NAME##_shrink_to_fit(NAME##_t *map) { \
    if (!map->size) { \
        NAME##_clear(map); \
        kama_deallocate(&map->options, map->heap, map->heap_bytes, NAME##_alignment()); \
        kama_options_t options = map->options; uint64_t hash_seed_delta = map->hash_seed_delta; \
        memset(map, 0, sizeof(*map)); map->options = options; map->hash_seed_delta = hash_seed_delta; \
        return 1; \
    } \
    size_t cap; if (!kama_capacity_for(map->size, &cap)) return 0; \
    return (cap == map->capacity && !map->tombstones) || NAME##_rehash(map, cap); \
} \
KAMA_HOT NAME##_location_t NAME##_prepare(NAME##_t *map, NAME##_keyarg_t key, uint64_t hash, int unique) { \
    NAME##_location_t failed = {SIZE_MAX, 0}; \
    if (!NAME##_valid_key(key)) return failed; \
    NAME##_location_t loc = NAME##_locate(map, key, hash, unique ? 2 : 1); \
    if (loc.found) return loc; \
    int grow = map->size >= map->resize_threshold; \
    int clean = map->capacity && loc.index != map->capacity && map->ctrl[loc.index] == KAMA_CTRL_EMPTY && \
                map->size + map->tombstones >= map->resize_threshold; \
    NAME##_staging_t stable; \
    if (grow || clean || loc.index == map->capacity) { \
        NAME##_stabilize_arg(&key, &stable); \
        size_t cap = map->capacity ? map->capacity : KAMA_GROUP_WIDTH; \
        if (grow && map->capacity) { \
            if (cap > SIZE_MAX / 2 || cap > UINT32_MAX) return failed; \
            cap *= 2; \
        } \
        /* Rebuild only once tombstones consumed the empty-slot budget; avoid \
         * repeated same-capacity rebuilds near maximum live occupancy. */ \
        if (clean && !grow && map->tombstones < map->capacity / 8) { \
            if (cap > SIZE_MAX / 2 || cap > UINT32_MAX) return failed; \
            cap *= 2; \
        } \
        if (!NAME##_rehash(map, cap)) return failed; \
        loc = NAME##_locate(map, key, hash, 2); \
    } \
    if (loc.index == map->capacity || !NAME##_store_key(map, loc.index, key, hash)) return failed; \
    if (map->ctrl[loc.index] == KAMA_CTRL_DELETED) --map->tombstones; \
    kama_set_ctrl(map->ctrl, map->capacity, loc.index, KAMA_H2(hash)); \
    ++map->size; return loc; \
} \
KAMA_FN int NAME##_erase_idx(NAME##_t *map, size_t i) { \
    if (i >= map->capacity || map->ctrl[i] < 0) return 0; \
    NAME##_drop_key(map, i); \
    int8_t tag = kama_can_erase_empty(map->ctrl, map->capacity, i) ? KAMA_CTRL_EMPTY : KAMA_CTRL_DELETED; \
    kama_set_ctrl(map->ctrl, map->capacity, i, tag); \
    --map->size; if (tag == KAMA_CTRL_DELETED) ++map->tombstones; \
    if (!map->size) { memset(map->ctrl, KAMA_CTRL_EMPTY, map->capacity + KAMA_GROUP_WIDTH); map->tombstones = 0; } \
    return 1; \
} \

#define KAMA_STRING_API(NAME, VAL_TYPE) \
typedef struct { VAL_TYPE *value; kama_result_t result; } NAME##_entry_t; \
KAMA_FN uint64_t NAME##_hash_key(const NAME##_t *map, const char *key, size_t len) { \
    NAME##_keyarg_t arg = {key, len}; \
    return NAME##_valid_key(arg) ? NAME##_hash_arg(map, arg) : 0; \
} \
KAMA_FN size_t NAME##_find_hashed(const NAME##_t *map, const char *key, size_t len, uint64_t hash) { \
    NAME##_keyarg_t arg = {key, len}; \
    return NAME##_valid_key(arg) ? NAME##_locate(map, arg, hash, 0).index : map->capacity; \
} \
KAMA_HOT size_t NAME##_find_idx(const NAME##_t *map, const char *key, size_t len) { \
    NAME##_keyarg_t arg = {key, len}; \
    if (!NAME##_valid_key(arg) || !map->capacity) return map->capacity; \
    return NAME##_locate(map, arg, NAME##_hash_arg(map, arg), 0).index; \
} \
KAMA_FN VAL_TYPE const *NAME##_get_ptr(const NAME##_t *map, const char *key, size_t len) { \
    size_t i = NAME##_find_idx(map, key, len); return i != map->capacity ? &map->slots[i].val : NULL; \
} \
KAMA_FN VAL_TYPE *NAME##_get_mut(NAME##_t *map, const char *key, size_t len) { \
    size_t i = NAME##_find_idx(map, key, len); return i != map->capacity ? &map->slots[i].val : NULL; \
} \
KAMA_FN int NAME##_get_hashed(const NAME##_t *map, const char *key, size_t len, uint64_t hash, VAL_TYPE *out) { \
    size_t i = NAME##_find_hashed(map, key, len, hash); \
    if (i == map->capacity) return 0; \
    if (out) *out = map->slots[i].val; \
    return 1; \
} \
KAMA_FN int NAME##_get(const NAME##_t *map, const char *key, size_t len, VAL_TYPE *out) { \
    size_t i = NAME##_find_idx(map, key, len); \
    if (i == map->capacity) return 0; \
    if (out) *out = map->slots[i].val; \
    return 1; \
} \
KAMA_FN int NAME##_contains(const NAME##_t *map, const char *key, size_t len) { return NAME##_find_idx(map, key, len) != map->capacity; } \
KAMA_FN kama_result_t NAME##_put_hashed(NAME##_t *map, const char *key, size_t len, VAL_TYPE val, uint64_t hash) { \
    NAME##_keyarg_t arg = {key, len}; \
    NAME##_location_t loc = NAME##_prepare(map, arg, hash, 0); \
    if (loc.index == SIZE_MAX) return KAMA_ERROR; \
    map->slots[loc.index].val = val; return loc.found ? KAMA_UPDATED : KAMA_INSERTED; \
} \
KAMA_FN kama_result_t NAME##_put(NAME##_t *map, const char *key, size_t len, VAL_TYPE val) { \
    return NAME##_put_hashed(map, key, len, val, NAME##_hash_key(map, key, len)); \
} \
/* Precondition: key is absent. This path intentionally skips equality checks. */ \
KAMA_FN kama_result_t NAME##_put_unique(NAME##_t *map, const char *key, size_t len, VAL_TYPE val) { \
    NAME##_keyarg_t arg = {key, len}; \
    NAME##_location_t loc = NAME##_prepare(map, arg, NAME##_hash_key(map, key, len), 1); \
    if (loc.index == SIZE_MAX) return KAMA_ERROR; \
    map->slots[loc.index].val = val; return KAMA_INSERTED; \
} \
KAMA_FN NAME##_entry_t NAME##_entry_hashed(NAME##_t *map, const char *key, size_t len, uint64_t hash) { \
    NAME##_keyarg_t arg = {key, len}; \
    NAME##_location_t loc = NAME##_prepare(map, arg, hash, 0); \
    NAME##_entry_t result = {NULL, KAMA_ERROR}; \
    if (loc.index == SIZE_MAX) return result; \
    result.value = &map->slots[loc.index].val; \
    result.result = loc.found ? KAMA_UPDATED : KAMA_INSERTED; \
    if (!loc.found) { VAL_TYPE zero = {0}; *result.value = zero; } \
    return result; \
} \
KAMA_FN NAME##_entry_t NAME##_entry(NAME##_t *map, const char *key, size_t len) { \
    return NAME##_entry_hashed(map, key, len, NAME##_hash_key(map, key, len)); \
} \
KAMA_FN kama_result_t NAME##_update(NAME##_t *map, const char *key, size_t len, void (*fn)(VAL_TYPE *, void *), void *context) { \
    if (!fn) return KAMA_ERROR; \
    NAME##_entry_t entry = NAME##_entry(map, key, len); \
    if (entry.value) fn(entry.value, context); \
    return entry.result; \
} \
KAMA_FN int NAME##_delete(NAME##_t *map, const char *key, size_t len) { return NAME##_erase_idx(map, NAME##_find_idx(map, key, len)); } \
KAMA_FN VAL_TYPE NAME##_val(const NAME##_t *map, size_t i) { return map->slots[i].val; } \
KAMA_FN size_t NAME##_get_batch(const NAME##_t *map, const NAME##_keyarg_t *keys, size_t count, VAL_TYPE *out, uint8_t *found) { \
    size_t hits = 0; \
    for (size_t begin = 0; begin < count;) { \
        size_t n = count - begin; if (n > KAMA_BATCH_SIZE) n = KAMA_BATCH_SIZE; \
        uint64_t hashes[KAMA_BATCH_SIZE]; \
        for (size_t j = 0; j < n; ++j) { \
            NAME##_keyarg_t arg = keys[begin + j]; \
            hashes[j] = NAME##_valid_key(arg) ? NAME##_hash_arg(map, arg) : 0; \
            if (map->capacity) KAMA_PREFETCH(map->ctrl + ((uint32_t)hashes[j] & (map->capacity - 1))); \
        } \
        for (size_t j = 0; j < n; ++j) { \
            NAME##_keyarg_t arg = keys[begin + j]; \
            size_t i = NAME##_valid_key(arg) ? NAME##_locate(map, arg, hashes[j], 0).index : map->capacity; \
            int hit = i != map->capacity; \
            if (found) found[begin + j] = (uint8_t)hit; \
            if (hit) { ++hits; if (out) out[begin + j] = map->slots[i].val; } \
        } \
        begin += n; \
    } \
    return hits; \
} \
/* Returns completed count. On error earlier writes remain; result[completed] is ERROR. */ \
KAMA_FN size_t NAME##_put_batch(NAME##_t *map, const NAME##_keyarg_t *keys, VAL_TYPE const *values, size_t count, kama_result_t *results) { \
    for (size_t begin = 0; begin < count;) { \
        size_t n = count - begin; if (n > KAMA_BATCH_SIZE) n = KAMA_BATCH_SIZE; \
        uint64_t hashes[KAMA_BATCH_SIZE]; \
        for (size_t j = 0; j < n; ++j) hashes[j] = NAME##_valid_key(keys[begin+j]) ? NAME##_hash_arg(map, keys[begin+j]) : 0; \
        for (size_t j = 0; j < n; ++j) { \
            size_t k = begin + j; \
            NAME##_location_t loc = NAME##_prepare(map, keys[k], hashes[j], 0); \
            kama_result_t result = loc.index == SIZE_MAX ? KAMA_ERROR : (loc.found ? KAMA_UPDATED : KAMA_INSERTED); \
            if (results) results[k] = result; \
            if (result == KAMA_ERROR) return k; \
            map->slots[loc.index].val = values[k]; \
        } \
        begin += n; \
    } \
    return count; \
} \

#define KAMA_STRING_SET_API(NAME) \
KAMA_FN uint64_t NAME##_hash_key(const NAME##_t *map, const char *key, size_t len) { \
    NAME##_keyarg_t arg = {key, len}; return NAME##_valid_key(arg) ? NAME##_hash_arg(map, arg) : 0; \
} \
KAMA_FN size_t NAME##_find_hashed(const NAME##_t *map, const char *key, size_t len, uint64_t hash) { \
    NAME##_keyarg_t arg = {key, len}; return NAME##_valid_key(arg) ? NAME##_locate(map, arg, hash, 0).index : map->capacity; \
} \
KAMA_HOT size_t NAME##_find_idx(const NAME##_t *map, const char *key, size_t len) { \
    NAME##_keyarg_t arg = {key, len}; \
    if (!NAME##_valid_key(arg) || !map->capacity) return map->capacity; \
    return NAME##_locate(map, arg, NAME##_hash_arg(map, arg), 0).index; \
} \
KAMA_FN int NAME##_contains(const NAME##_t *map, const char *key, size_t len) { return NAME##_find_idx(map, key, len) != map->capacity; } \
KAMA_FN kama_result_t NAME##_insert_hashed(NAME##_t *map, const char *key, size_t len, uint64_t hash) { \
    NAME##_keyarg_t arg = {key, len}; NAME##_location_t loc = NAME##_prepare(map, arg, hash, 0); \
    return loc.index == SIZE_MAX ? KAMA_ERROR : (loc.found ? KAMA_UPDATED : KAMA_INSERTED); \
} \
KAMA_FN kama_result_t NAME##_insert(NAME##_t *map, const char *key, size_t len) { return NAME##_insert_hashed(map, key, len, NAME##_hash_key(map, key, len)); } \
KAMA_FN int NAME##_delete(NAME##_t *map, const char *key, size_t len) { return NAME##_erase_idx(map, NAME##_find_idx(map, key, len)); } \
KAMA_FN size_t NAME##_contains_batch(const NAME##_t *map, const NAME##_keyarg_t *keys, size_t count, uint8_t *found) { \
    size_t hits = 0; \
    for (size_t begin = 0; begin < count;) { \
        size_t n = count - begin; if (n > KAMA_BATCH_SIZE) n = KAMA_BATCH_SIZE; \
        uint64_t hashes[KAMA_BATCH_SIZE]; \
        for (size_t j=0;j<n;++j) { \
            hashes[j] = NAME##_valid_key(keys[begin+j]) ? NAME##_hash_arg(map, keys[begin+j]) : 0; \
            if (map->capacity) KAMA_PREFETCH(map->ctrl + ((uint32_t)hashes[j] & (map->capacity-1))); \
        } \
        for (size_t j=0;j<n;++j) { \
            NAME##_keyarg_t arg = keys[begin+j]; \
            int hit = NAME##_valid_key(arg) && NAME##_locate(map, arg, hashes[j], 0).index != map->capacity; \
            hits += (size_t)hit; if (found) found[begin+j] = (uint8_t)hit; \
        } \
        begin += n; \
    } \
    return hits; \
} \
KAMA_FN size_t NAME##_insert_batch(NAME##_t *map, const NAME##_keyarg_t *keys, size_t count, kama_result_t *results) { \
    for (size_t i=0;i<count;++i) { \
        NAME##_keyarg_t key = keys[i]; \
        uint64_t hash = NAME##_valid_key(key) ? NAME##_hash_arg(map, key) : 0; \
        NAME##_location_t loc = NAME##_prepare(map,key,hash,0); \
        kama_result_t result = loc.index == SIZE_MAX ? KAMA_ERROR : (loc.found ? KAMA_UPDATED : KAMA_INSERTED); \
        if (results) results[i] = result; \
        if (result == KAMA_ERROR) return i; \
    } \
    return count; \
} \

#define KAMA_FIXED_API(NAME, VAL_TYPE) \
typedef struct { VAL_TYPE *value; kama_result_t result; } NAME##_entry_t; \
KAMA_FN uint64_t NAME##_hash_key(const NAME##_t *map, NAME##_keyarg_t key) { \
    NAME##_keyarg_t arg = key; \
    return NAME##_valid_key(arg) ? NAME##_hash_arg(map, arg) : 0; \
} \
KAMA_FN size_t NAME##_find_hashed(const NAME##_t *map, NAME##_keyarg_t key, uint64_t hash) { \
    NAME##_keyarg_t arg = key; \
    return NAME##_valid_key(arg) ? NAME##_locate(map, arg, hash, 0).index : map->capacity; \
} \
KAMA_HOT size_t NAME##_find_idx(const NAME##_t *map, NAME##_keyarg_t key) { \
    NAME##_keyarg_t arg = key; \
    if (!NAME##_valid_key(arg) || !map->capacity) return map->capacity; \
    return NAME##_locate(map, arg, NAME##_hash_arg(map, arg), 0).index; \
} \
KAMA_FN VAL_TYPE const *NAME##_get_ptr(const NAME##_t *map, NAME##_keyarg_t key) { \
    size_t i = NAME##_find_idx(map, key); return i != map->capacity ? &map->slots[i].val : NULL; \
} \
KAMA_FN VAL_TYPE *NAME##_get_mut(NAME##_t *map, NAME##_keyarg_t key) { \
    size_t i = NAME##_find_idx(map, key); return i != map->capacity ? &map->slots[i].val : NULL; \
} \
KAMA_FN int NAME##_get_hashed(const NAME##_t *map, NAME##_keyarg_t key, uint64_t hash, VAL_TYPE *out) { \
    size_t i = NAME##_find_hashed(map, key, hash); \
    if (i == map->capacity) return 0; \
    if (out) *out = map->slots[i].val; \
    return 1; \
} \
KAMA_FN int NAME##_get(const NAME##_t *map, NAME##_keyarg_t key, VAL_TYPE *out) { \
    size_t i = NAME##_find_idx(map, key); \
    if (i == map->capacity) return 0; \
    if (out) *out = map->slots[i].val; \
    return 1; \
} \
KAMA_FN int NAME##_contains(const NAME##_t *map, NAME##_keyarg_t key) { return NAME##_find_idx(map, key) != map->capacity; } \
KAMA_FN kama_result_t NAME##_put_hashed(NAME##_t *map, NAME##_keyarg_t key, VAL_TYPE val, uint64_t hash) { \
    NAME##_keyarg_t arg = key; \
    NAME##_location_t loc = NAME##_prepare(map, arg, hash, 0); \
    if (loc.index == SIZE_MAX) return KAMA_ERROR; \
    map->slots[loc.index].val = val; return loc.found ? KAMA_UPDATED : KAMA_INSERTED; \
} \
KAMA_FN kama_result_t NAME##_put(NAME##_t *map, NAME##_keyarg_t key, VAL_TYPE val) { \
    return NAME##_put_hashed(map, key, val, NAME##_hash_key(map, key)); \
} \
/* Precondition: key is absent. This path intentionally skips equality checks. */ \
KAMA_FN kama_result_t NAME##_put_unique(NAME##_t *map, NAME##_keyarg_t key, VAL_TYPE val) { \
    NAME##_keyarg_t arg = key; \
    NAME##_location_t loc = NAME##_prepare(map, arg, NAME##_hash_key(map, key), 1); \
    if (loc.index == SIZE_MAX) return KAMA_ERROR; \
    map->slots[loc.index].val = val; return KAMA_INSERTED; \
} \
KAMA_FN NAME##_entry_t NAME##_entry_hashed(NAME##_t *map, NAME##_keyarg_t key, uint64_t hash) { \
    NAME##_keyarg_t arg = key; \
    NAME##_location_t loc = NAME##_prepare(map, arg, hash, 0); \
    NAME##_entry_t result = {NULL, KAMA_ERROR}; \
    if (loc.index == SIZE_MAX) return result; \
    result.value = &map->slots[loc.index].val; \
    result.result = loc.found ? KAMA_UPDATED : KAMA_INSERTED; \
    if (!loc.found) { VAL_TYPE zero = {0}; *result.value = zero; } \
    return result; \
} \
KAMA_FN NAME##_entry_t NAME##_entry(NAME##_t *map, NAME##_keyarg_t key) { \
    return NAME##_entry_hashed(map, key, NAME##_hash_key(map, key)); \
} \
KAMA_FN kama_result_t NAME##_update(NAME##_t *map, NAME##_keyarg_t key, void (*fn)(VAL_TYPE *, void *), void *context) { \
    if (!fn) return KAMA_ERROR; \
    NAME##_entry_t entry = NAME##_entry(map, key); \
    if (entry.value) fn(entry.value, context); \
    return entry.result; \
} \
KAMA_FN int NAME##_delete(NAME##_t *map, NAME##_keyarg_t key) { return NAME##_erase_idx(map, NAME##_find_idx(map, key)); } \
KAMA_FN VAL_TYPE NAME##_val(const NAME##_t *map, size_t i) { return map->slots[i].val; } \
KAMA_FN size_t NAME##_get_batch(const NAME##_t *map, const NAME##_keyarg_t *keys, size_t count, VAL_TYPE *out, uint8_t *found) { \
    size_t hits = 0; \
    for (size_t begin = 0; begin < count;) { \
        size_t n = count - begin; if (n > KAMA_BATCH_SIZE) n = KAMA_BATCH_SIZE; \
        uint64_t hashes[KAMA_BATCH_SIZE]; \
        for (size_t j = 0; j < n; ++j) { \
            NAME##_keyarg_t arg = keys[begin + j]; \
            hashes[j] = NAME##_valid_key(arg) ? NAME##_hash_arg(map, arg) : 0; \
            if (map->capacity) KAMA_PREFETCH(map->ctrl + ((uint32_t)hashes[j] & (map->capacity - 1))); \
        } \
        for (size_t j = 0; j < n; ++j) { \
            NAME##_keyarg_t arg = keys[begin + j]; \
            size_t i = NAME##_valid_key(arg) ? NAME##_locate(map, arg, hashes[j], 0).index : map->capacity; \
            int hit = i != map->capacity; \
            if (found) found[begin + j] = (uint8_t)hit; \
            if (hit) { ++hits; if (out) out[begin + j] = map->slots[i].val; } \
        } \
        begin += n; \
    } \
    return hits; \
} \
/* Returns completed count. On error earlier writes remain; result[completed] is ERROR. */ \
KAMA_FN size_t NAME##_put_batch(NAME##_t *map, const NAME##_keyarg_t *keys, VAL_TYPE const *values, size_t count, kama_result_t *results) { \
    for (size_t begin = 0; begin < count;) { \
        size_t n = count - begin; if (n > KAMA_BATCH_SIZE) n = KAMA_BATCH_SIZE; \
        uint64_t hashes[KAMA_BATCH_SIZE]; \
        for (size_t j = 0; j < n; ++j) hashes[j] = NAME##_valid_key(keys[begin+j]) ? NAME##_hash_arg(map, keys[begin+j]) : 0; \
        for (size_t j = 0; j < n; ++j) { \
            size_t k = begin + j; \
            NAME##_location_t loc = NAME##_prepare(map, keys[k], hashes[j], 0); \
            kama_result_t result = loc.index == SIZE_MAX ? KAMA_ERROR : (loc.found ? KAMA_UPDATED : KAMA_INSERTED); \
            if (results) results[k] = result; \
            if (result == KAMA_ERROR) return k; \
            map->slots[loc.index].val = values[k]; \
        } \
        begin += n; \
    } \
    return count; \
} \

#define KAMA_FIXED_SET_API(NAME) \
KAMA_FN uint64_t NAME##_hash_key(const NAME##_t *map, NAME##_keyarg_t key) { \
    NAME##_keyarg_t arg = key; return NAME##_valid_key(arg) ? NAME##_hash_arg(map, arg) : 0; \
} \
KAMA_FN size_t NAME##_find_hashed(const NAME##_t *map, NAME##_keyarg_t key, uint64_t hash) { \
    NAME##_keyarg_t arg = key; return NAME##_valid_key(arg) ? NAME##_locate(map, arg, hash, 0).index : map->capacity; \
} \
KAMA_HOT size_t NAME##_find_idx(const NAME##_t *map, NAME##_keyarg_t key) { \
    NAME##_keyarg_t arg = key; \
    if (!NAME##_valid_key(arg) || !map->capacity) return map->capacity; \
    return NAME##_locate(map, arg, NAME##_hash_arg(map, arg), 0).index; \
} \
KAMA_FN int NAME##_contains(const NAME##_t *map, NAME##_keyarg_t key) { return NAME##_find_idx(map, key) != map->capacity; } \
KAMA_FN kama_result_t NAME##_insert_hashed(NAME##_t *map, NAME##_keyarg_t key, uint64_t hash) { \
    NAME##_keyarg_t arg = key; NAME##_location_t loc = NAME##_prepare(map, arg, hash, 0); \
    return loc.index == SIZE_MAX ? KAMA_ERROR : (loc.found ? KAMA_UPDATED : KAMA_INSERTED); \
} \
KAMA_FN kama_result_t NAME##_insert(NAME##_t *map, NAME##_keyarg_t key) { return NAME##_insert_hashed(map, key, NAME##_hash_key(map, key)); } \
KAMA_FN int NAME##_delete(NAME##_t *map, NAME##_keyarg_t key) { return NAME##_erase_idx(map, NAME##_find_idx(map, key)); } \
KAMA_FN size_t NAME##_contains_batch(const NAME##_t *map, const NAME##_keyarg_t *keys, size_t count, uint8_t *found) { \
    size_t hits = 0; \
    for (size_t begin = 0; begin < count;) { \
        size_t n = count - begin; if (n > KAMA_BATCH_SIZE) n = KAMA_BATCH_SIZE; \
        uint64_t hashes[KAMA_BATCH_SIZE]; \
        for (size_t j=0;j<n;++j) { \
            hashes[j] = NAME##_valid_key(keys[begin+j]) ? NAME##_hash_arg(map, keys[begin+j]) : 0; \
            if (map->capacity) KAMA_PREFETCH(map->ctrl + ((uint32_t)hashes[j] & (map->capacity-1))); \
        } \
        for (size_t j=0;j<n;++j) { \
            NAME##_keyarg_t arg = keys[begin+j]; \
            int hit = NAME##_valid_key(arg) && NAME##_locate(map, arg, hashes[j], 0).index != map->capacity; \
            hits += (size_t)hit; if (found) found[begin+j] = (uint8_t)hit; \
        } \
        begin += n; \
    } \
    return hits; \
} \
KAMA_FN size_t NAME##_insert_batch(NAME##_t *map, const NAME##_keyarg_t *keys, size_t count, kama_result_t *results) { \
    for (size_t i=0;i<count;++i) { \
        NAME##_keyarg_t key = keys[i]; \
        uint64_t hash = NAME##_valid_key(key) ? NAME##_hash_arg(map, key) : 0; \
        NAME##_location_t loc = NAME##_prepare(map,key,hash,0); \
        kama_result_t result = loc.index == SIZE_MAX ? KAMA_ERROR : (loc.found ? KAMA_UPDATED : KAMA_INSERTED); \
        if (results) results[i] = result; \
        if (result == KAMA_ERROR) return i; \
    } \
    return count; \
} \

#define kama(NAME, VAL_TYPE) \
KAMA_CHECK_VALUE(VAL_TYPE) \
KAMA_DECLARE(NAME, kama_key_t, kama_string_storage_t, kama_meta_t, sizeof(kama_meta_t), 0, VAL_TYPE val;) \
KAMA_STRING(NAME, map->meta + i) \
KAMA_TABLE(NAME) \
KAMA_STRING_API(NAME, VAL_TYPE) \

#define kama_set(NAME) \
KAMA_DECLARE(NAME, kama_key_t, kama_string_storage_t, kama_meta_t, sizeof(kama_meta_t), 0, ) \
KAMA_STRING(NAME, map->meta + i) \
KAMA_TABLE(NAME) \
KAMA_STRING_SET_API(NAME) \

#define kama_soa(NAME, VAL_TYPE) \
KAMA_CHECK_VALUE(VAL_TYPE) \
KAMA_DECLARE(NAME, kama_key_t, kama_string_storage_t, kama_meta_t, sizeof(kama_meta_t), 0, VAL_TYPE val;) \
KAMA_STRING(NAME, map->meta + i) \
KAMA_TABLE(NAME) \
KAMA_STRING_API(NAME, VAL_TYPE) \

#define kama_soa_set(NAME) \
KAMA_DECLARE(NAME, kama_key_t, kama_string_storage_t, kama_meta_t, sizeof(kama_meta_t), 0, ) \
KAMA_STRING(NAME, map->meta + i) \
KAMA_TABLE(NAME) \
KAMA_STRING_SET_API(NAME) \

#define kama_packed(NAME, VAL_TYPE) \
KAMA_CHECK_VALUE(VAL_TYPE) \
KAMA_DECLARE(NAME, kama_key_t, kama_string_storage_t, kama_meta_t, 0, 1, kama_meta_t metadata; VAL_TYPE val;) \
typedef char NAME##_packed_layout[(sizeof(kama_string_storage_t) == 8 && offsetof(NAME##_pair_t, metadata) == 8) ? 1 : -1]; \
KAMA_STRING(NAME, &map->slots[i].metadata) \
KAMA_TABLE(NAME) \
KAMA_STRING_API(NAME, VAL_TYPE) \

#define kama_packed_set(NAME) \
KAMA_DECLARE(NAME, kama_key_t, kama_string_storage_t, kama_meta_t, 0, 1, kama_meta_t metadata; ) \
typedef char NAME##_packed_layout[(sizeof(kama_string_storage_t) == 8 && offsetof(NAME##_pair_t, metadata) == 8) ? 1 : -1]; \
KAMA_STRING(NAME, &map->slots[i].metadata) \
KAMA_TABLE(NAME) \
KAMA_STRING_SET_API(NAME) \

#define kama_aos(NAME, VAL_TYPE) \
KAMA_CHECK_VALUE(VAL_TYPE) \
KAMA_DECLARE(NAME, kama_key_t, kama_string_storage_t, kama_meta_t, 0, 0, kama_meta_t metadata; VAL_TYPE val;) \
typedef char NAME##_packed_layout[(sizeof(kama_string_storage_t) == 8 && offsetof(NAME##_pair_t, metadata) == 8) ? 1 : -1]; \
KAMA_STRING(NAME, &map->slots[i].metadata) \
KAMA_TABLE(NAME) \
KAMA_STRING_API(NAME, VAL_TYPE) \

#define kama_aos_set(NAME) \
KAMA_DECLARE(NAME, kama_key_t, kama_string_storage_t, kama_meta_t, 0, 0, kama_meta_t metadata; ) \
typedef char NAME##_packed_layout[(sizeof(kama_string_storage_t) == 8 && offsetof(NAME##_pair_t, metadata) == 8) ? 1 : -1]; \
KAMA_STRING(NAME, &map->slots[i].metadata) \
KAMA_TABLE(NAME) \
KAMA_STRING_SET_API(NAME) \

#define kama_u32(NAME, VAL_TYPE) \
KAMA_CHECK_VALUE(VAL_TYPE) \
KAMA_DECLARE(NAME, uint32_t, uint32_t, uint8_t, 0, 0, VAL_TYPE val;) \
KAMA_FIXED(NAME, 1, &key, kama_hash_integer32(key, map->options.seed), uint32_t, map->slots[i].key, map->slots[i].key == key, map->slots[i].key, *storage) \
KAMA_TABLE(NAME) \
KAMA_FIXED_API(NAME, VAL_TYPE) \

#define kama_u32_set(NAME) \
KAMA_DECLARE(NAME, uint32_t, uint32_t, uint8_t, 0, 0, ) \
KAMA_FIXED(NAME, 1, &key, kama_hash_integer32(key, map->options.seed), uint32_t, map->slots[i].key, map->slots[i].key == key, map->slots[i].key, *storage) \
KAMA_TABLE(NAME) \
KAMA_FIXED_SET_API(NAME) \

#define kama_u64(NAME, VAL_TYPE) \
KAMA_CHECK_VALUE(VAL_TYPE) \
KAMA_DECLARE(NAME, uint64_t, uint64_t, uint8_t, 0, 0, VAL_TYPE val;) \
KAMA_FIXED(NAME, 1, &key, kama_hash_u64((uint64_t)key ^ map->options.seed), uint64_t, map->slots[i].key, map->slots[i].key == key, map->slots[i].key, *storage) \
KAMA_TABLE(NAME) \
KAMA_FIXED_API(NAME, VAL_TYPE) \

#define kama_u64_set(NAME) \
KAMA_DECLARE(NAME, uint64_t, uint64_t, uint8_t, 0, 0, ) \
KAMA_FIXED(NAME, 1, &key, kama_hash_u64((uint64_t)key ^ map->options.seed), uint64_t, map->slots[i].key, map->slots[i].key == key, map->slots[i].key, *storage) \
KAMA_TABLE(NAME) \
KAMA_FIXED_SET_API(NAME) \

#define kama_ptr(NAME, VAL_TYPE) \
KAMA_CHECK_VALUE(VAL_TYPE) \
KAMA_DECLARE(NAME, const void *, const void *, uint8_t, 0, 0, VAL_TYPE val;) \
KAMA_FIXED(NAME, 1, &key, kama_hash_u64((uint64_t)(uintptr_t)key ^ map->options.seed), const void *, map->slots[i].key, map->slots[i].key == key, map->slots[i].key, *storage) \
KAMA_TABLE(NAME) \
KAMA_FIXED_API(NAME, VAL_TYPE) \

#define kama_ptr_set(NAME) \
KAMA_DECLARE(NAME, const void *, const void *, uint8_t, 0, 0, ) \
KAMA_FIXED(NAME, 1, &key, kama_hash_u64((uint64_t)(uintptr_t)key ^ map->options.seed), const void *, map->slots[i].key, map->slots[i].key == key, map->slots[i].key, *storage) \
KAMA_TABLE(NAME) \
KAMA_FIXED_SET_API(NAME) \

#define kama_fixed(NAME, N, VAL_TYPE) \
KAMA_CHECK_VALUE(VAL_TYPE) \
typedef char NAME##_positive_key_size[(N) > 0 ? 1 : -1]; \
typedef struct { unsigned char bytes[N]; } NAME##_fixed_key_t; \
KAMA_DECLARE(NAME, const void *, NAME##_fixed_key_t, uint8_t, 0, 0, VAL_TYPE val;) \
KAMA_FIXED(NAME, key != NULL, key, (sizeof(NAME##_storage_t) <= 16 ? kama_hash_short((const char *)key, sizeof(NAME##_storage_t), map->hash_seed_delta ^ kama_prepare_hash_seed(0)) : kama_rapidhash((const char *)key, sizeof(NAME##_storage_t), map->options.seed)), const void *, &map->slots[i].key, memcmp(&map->slots[i].key, key, sizeof(NAME##_storage_t)) == 0, &map->slots[i].key, (const void *)storage) \
KAMA_TABLE(NAME) \
KAMA_FIXED_API(NAME, VAL_TYPE) \

#define kama_fixed_set(NAME, N) \
typedef char NAME##_positive_key_size[(N) > 0 ? 1 : -1]; \
typedef struct { unsigned char bytes[N]; } NAME##_fixed_key_t; \
KAMA_DECLARE(NAME, const void *, NAME##_fixed_key_t, uint8_t, 0, 0, ) \
KAMA_FIXED(NAME, key != NULL, key, (sizeof(NAME##_storage_t) <= 16 ? kama_hash_short((const char *)key, sizeof(NAME##_storage_t), map->hash_seed_delta ^ kama_prepare_hash_seed(0)) : kama_rapidhash((const char *)key, sizeof(NAME##_storage_t), map->options.seed)), const void *, &map->slots[i].key, memcmp(&map->slots[i].key, key, sizeof(NAME##_storage_t)) == 0, &map->slots[i].key, (const void *)storage) \
KAMA_TABLE(NAME) \
KAMA_FIXED_SET_API(NAME) \

#define kama_foreach(MAP, INDEX) \
    for (size_t INDEX = 0; INDEX < (MAP)->capacity; ++INDEX) \
        if ((MAP)->ctrl[INDEX] >= 0)

#endif /* KAMA_H */
